### ISSUE TITLE
签名验证问题 :)

### ISSUE THREAD

**Issue by ChrisLeeGit** [fzlee/alipay#10]
Hello, 非常感谢你提供的这个支付宝 API SDK。学习了很多。
关于签名验证这块，[支付宝文档](https://doc.open.alipay.com/docs/doc.htm?docType=1&articleId=106120) 一节说只对返回的 `xx_response` 的内容进行校验。目前的代码中好像没有这种验证方式吧，不知道能不能帮忙看看。Thanks

**Comment by fzlee** [comment]
同步验签和异步验签的技术实现原理应该差不多，异步需要验签是为了验证请求确实来自支付宝，而同步不太需要，是因为我们向支付宝发起HTTP请求时，已经验证了它的HTTPS证书。

不过多验证一步也没有问题，我稍后会添加这个功能

**Comment by ChrisLeeGit** [comment]
OK，多谢！目前我也实现了同步响应验签的功能，不过感觉写得不太好，到时候可以学习下你的代码 👍

**Comment by fzlee** [comment]
暂时推送到了dev， 我好想明白你是怎么纠结同步验签功能的了，获取待验证的字符串有点麻烦，你可以看看这个函数`__get_string_to_be_signed`，应该没有什么问题的

**Comment by ChrisLeeGit** [comment]
同步验签比较麻烦，因为要保证原先 `response` 中的 `key-value` 顺序。我是用下面的方式先将 `json` 字符串提取成有序字典，从而保持原先的顺序不乱：
```
def load_from_json_text(text, keep_order=True):
    """
    加载 json 格式的文本
    """
    from json import loads
    from collections import OrderedDict

    if keep_order is True:
        return loads(text, object_pairs_hook=OrderedDict)
    else:
        return loads(text)
```

然后将 `xxx_response` 提取出来（仍然是有序字典）后再转回 `json` 字符串，参见下面的函数。在重新转成 json 字符串时，要把 `,`, `:` 两边空格去掉，才能和原先的字符串一致。：
```
def to_json_text(data=None, sort_keys=True):
    """
    用于将字典转换成有序的字符串 JSON

    :param data: 字典数据
    :param sort_keys: 是否排序
    :return:
    """
    from json import dumps
    assert isinstance(data, dict)

    return dumps(data, ensure_ascii=False, sort_keys=sort_keys, separators=(',', ':'))
```

总的来说，也挺麻烦，不过多多借助了 `json` 模块。
:)

**Comment by fzlee** [comment]
感觉你的方法好一点
