### ISSUE TITLE
from alipay import AliPay请问您是怎么跑通的？

### ISSUE THREAD

**Issue by appleyuchi** [fzlee/alipay#101]
from alipay import AliPay
ImportError: cannot import name 'AliPay' from 'alipay' (/home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/alipay/__init__.py)

**Comment by fzlee** [comment]
你使用的alipay版本是多少.

打开一下这个文件, /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/alipay/__init__.py
 看里面是些什么内容

**Comment by appleyuchi** [comment]
`(python3.7) appleyuchi@ubuntu19:~$ cat /home/appleyuchi/.virtualenvs/python3.7/lib/python3.7/site-packages/alipay/__init__.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    __inti__.py
"""
name = "alipay-sdk-python"
__version__ = "3.3.398"
`
不知道怎么排版格式，见谅

**Comment by appleyuchi** [comment]
几乎所有网上django接入支付宝的博客都是
from alipay import Alipay

**Comment by appleyuchi** [comment]
pip和下载源码包的安装方式我都试过了，都无法运行．．．．
然后我看了下包里面各种Alipayxxxxxxxxxx的类，头大．
这是要重写views.py的节奏吗?
我本来只是想跑一下流程．

**Comment by fzlee** [comment]
__init__.py 文件里面并不是我的源代码, 感觉你并没有安装这个库.

首先你试试 `pip install python-alipay-sdk --upgrade`

然后运行如下代码
```
lib_path=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`; cd $lib_path
```

可以进入到python库的目录, cd alipay, alipay目录里面的文件内容应该和这个github上显示的一样


### 关于跑一下测试流程
你直接拷贝这个项目, 把这个项目的alipay目录直接拿出来,安装相关的依赖之后应该就可以使用了.
并不需要配合django使用.

参见 中文的文档的`电脑网站支付`部分, 生成order_string 之后,
```
https://openapi.alipay.com/gateway.do? + order_strring
```
在浏览器打开, 可以直接跳转到支付宝支付.

**Comment by appleyuchi** [comment]
这个库我安装了不下五遍啊．．．

**Comment by appleyuchi** [comment]
(python3.7) appleyuchi@ubuntu19:alipay$ python
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alipay import Alipay
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Alipay' from 'alipay' (/home/appleyuchi/桌面/Django接入支付宝/库安装/alipay/alipay/__init__.py)
下载这个项目后，还是跑不了，到底应该怎么使用呢？感谢

**Comment by appleyuchi** [comment]
下载后显示的是:
class AliPay(BaseAliPay):
    pass

**Comment by appleyuchi** [comment]
我看了下我安装的包：
(python3.7) appleyuchi@ubuntu19:~$ pip list|grep alipay
alipay-sdk-python        3.3.398      
python-alipay-sdk        2.0.1

**Comment by fzlee** [comment]
```
from alipay import AliPay
```
大小写错了

**Comment by appleyuchi** [comment]
`from alipay import AliPay`

**Comment by appleyuchi** [comment]
博客上都是这个啊．

**Comment by fzlee** [comment]
你装了两个包, 一个是alipay-sdk-python,这个是阿里官方的库
一个是python-alipay-sdk, 这个是我的库.

这两个库是冲突的

**Comment by appleyuchi** [comment]
搞定了，感谢

**Comment by EmiyaKiritsugu-hash** [comment]
fzlee你好，我严格按照你的文档格式尝试了一下，一直说Appid错误，是需要什么windows特殊配置吗

**Comment by EmiyaKiritsugu-hash** [comment]
app_private_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/app_private_key.pem')).read()
        alipay_public_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/alipay_public_key.pem')).read()
        print(app_private_key_string)
        print(alipay_public_key_string)
        alipay = AliPay(
        appid="2016101700710750",
        app_notify_url=None,  # 默认回调url
        app_private_key_string=app_private_key_string,
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2", # RSA 或者 RSA2
        debug=True  # 默认False
        )
        total_pay = order.total_price + order.transit_price
        order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order.order_id,
        total_amount=str(total_pay),
        subject='天天生鲜'+order.order_id,
        return_url=None,
        notify_url=None # 可选, 不填则使用默认notify url
        ) 
        pat_url = 'https://openapi.alipay.com/gateway.do?' + order_string
        return JsonResponse({'res': 4,'pay_url':pat_url, 'message':'跳转支付页面'})

**Comment by EmiyaKiritsugu-hash** [comment]
from alipay import AliPay
app_private_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/app_private_key.pem')).read()
        alipay_public_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/alipay_public_key.pem')).read()
        print(app_private_key_string)
        print(alipay_public_key_string)
        alipay = AliPay(
        appid="2016101700710750",
        app_notify_url=None,  # 默认回调url
        app_private_key_string=app_private_key_string,
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2", # RSA 或者 RSA2
        debug=True  # 默认False
        )
        total_pay = order.total_price + order.transit_price
        order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order.order_id,
        total_amount=str(total_pay),
        subject='天天生鲜'+order.order_id,
        return_url=None,
        notify_url=None # 可选, 不填则使用默认notify url
        ) 
        pat_url = 'https://openapi.alipay.com/gateway.do?' + order_string
        return JsonResponse({'res': 4,'pay_url':pat_url, 'message':'跳转支付页面'})


这是相关部分的代码，如果有空的话可以帮我看一下吗

**Comment by EmiyaKiritsugu-hash** [comment]
from alipay import AliPay
app_private_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/app_private_key.pem')).read()
        alipay_public_key_string = open(os.path.join(settings.BASE_DIR,'apps/order/alipay_public_key.pem')).read()
        print(app_private_key_string)
        print(alipay_public_key_string)
        alipay = AliPay(
        appid=settings.AppID,
        app_notify_url=None,  # 默认回调url
        app_private_key_string=app_private_key_string,
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        alipay_public_key_string=alipay_public_key_string,
        sign_type="RSA2", # RSA 或者 RSA2
        debug=True  # 默认False
        )
        total_pay = order.total_price + order.transit_price
        order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order.order_id,
        total_amount=str(total_pay),
        subject='天天生鲜'+order.order_id,
        return_url=None,
        notify_url=None # 可选, 不填则使用默认notify url
        ) 
        pat_url = 'https://openapi.alipay.com/gateway.do?' + order_string
        return JsonResponse({'res': 4,'pay_url':pat_url, 'message':'跳转支付页面'})

这是相关部分的代码，也尝试过直接将id写进去，但还是报错：
错误代码 invalid-app-id 错误原因: 无效的AppID参数

**Comment by fzlee** [comment]
debug 改成False

True的话, 请求会被传递到支付宝的测试环境

**Comment by EmiyaKiritsugu-hash** [comment]
我就是在测试环境的，沙箱，所以改成True。

**Comment by fzlee** [comment]
沙箱的URL 应该不是 https://openapi.alipay.com/gateway.do

**Comment by EmiyaKiritsugu-hash** [comment]
哇   是我傻逼了  我去看看

**Comment by EmiyaKiritsugu-hash** [comment]
可以了，弄了半天原来是这个没改，真是太蠢了。 谢谢你
