### ISSUE TITLE
报错_openssl.abi3.so: undefined symbol: OPENSSL_sk_num

### ISSUE THREAD

**Issue by 354446617** [fzlee/alipay#103]
ImportError at /user/order/1

/home/wy/software/anaconda3/envs/dailyfresh/lib/python3.4/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: OPENSSL_sk_num

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/user/order/1
Django Version: 	1.8.2
Exception Type: 	ImportError
Exception Value: 	

/home/wy/software/anaconda3/envs/dailyfresh/lib/python3.4/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: OPENSSL_sk_num

Exception Location: 	/home/wy/software/anaconda3/envs/dailyfresh/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py in <module>, line 15
Python Executable: 	/home/wy/software/anaconda3/envs/dailyfresh/bin/python
Python Version: 	3.4.5
另外其他一些依赖包的版本：
pyopenssl                 19.1.0
pycryptodomex             3.9.4
python-alipay-sdk         2.0.1 
cryptography              2.8
cffi==1.14.0
certifi==2019.11.28

现在进每个页面都报错ImportError at xxx

**Comment by fzlee** [comment]
操作系统和openssl的版本各是多少?

openssl是自己编译的吗

**Comment by 354446617** [comment]
我之后安装了python-alipay-sdk1.7版本可以了，应该是版本兼容的问题，谢谢拉~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fzlee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 下午2:41
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"JesseWang"<354446617@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] 报错_openssl.abi3.so: undefined symbol: OPENSSL_sk_num (#103)





 
操作系统和openssl的版本各是多少?
 
openssl是自己编译的吗
