### ISSUE TITLE
初始化钥匙文件问题

### ISSUE THREAD

**Issue by jackwu882002** [fzlee/alipay#107]
第一部分：
app_private_key_string = open("/path/to/your/private/key.pem").read()
alipay_public_key_string = open("/path/to/alipay/public/key.pem").read()

第2部分：
app_private_key_string == """
    -----BEGIN RSA PRIVATE KEY-----
    base64 encoded content
    -----END RSA PRIVATE KEY-----
"""

alipay_public_key_string == """
    -----BEGIN PUBLIC KEY-----
    base64 encoded content
    -----END PUBLIC KEY-----
"""
请问第一、二部分是任意设置一个，还是两个都要设置才行？

/path/to/your/private/key.pem 这个路径需要是文件夹绝对路径，需要 import os 么？
谢谢

**Comment by fzlee** [comment]
任意设置一个就行了,
第一部分的代码是在演示从本地文件读取公钥私钥
第二部分的代码实在演示从字符串直接加载公钥私钥.

本地文件读取比较合适, 一般不建议私钥直接放在代码里面.
第二部分的应用场景是从数据库或者第三方服务获取公钥私钥之后初始化Alipay.


需要import os, 可能需要用类似`os.path.dirname(__file__))`的方法获取证书文件的绝对路径

**Comment by jackwu882002** [comment]
谢谢了， 我直接设置绝对项目路径就行了，不用os.path...
