### ISSUE TITLE
Can you add applet program alipay pay? 

### ISSUE THREAD

**Issue by zhujincheng** [fzlee/alipay#108]

**Comment by fzlee** [comment]
有文档吗

**Comment by zhujincheng** [comment]
> 有文档吗

https://opendocs.alipay.com/mini/introduce/pay

**Comment by zhujincheng** [comment]
> 有文档吗

2.0版本回调验签不通过 我又回退到1版本了

**Comment by fzlee** [comment]
我会在最近添加这个函数

**Comment by zhujincheng** [comment]
给力

**Comment by zhtfish** [comment]
> 我会在最近添加这个函数
请问fzlee大神，付完款后回调验签l老是不通过，请问源码有更新了吗？谢谢

**Comment by fzlee** [comment]
@zhtfish 发代码上来看看吧

**Comment by fzlee** [comment]
@zhujincheng 小程序支付已经添加, 本地不太方便测试, 你有时间可以帮忙测一测
