### ISSUE TITLE
wap支付的时候有bug

### ISSUE THREAD

**Issue by coffeefoam** [fzlee/alipay#11]
create_wap_trade方法里，biz_content最终并没有赋值，会造成跳转到支付宝支付时出现 ALI38173错误

**Comment by fzlee** [comment]
0.6.5 已经修复了，你可以帮忙测试一下

**Comment by coffeefoam** [comment]
pip还只能安装0.6.4吧

**Comment by fzlee** [comment]
你用的是非官方源吗，可能同步会晚一点。pypi上的已经是最新了
