### ISSUE TITLE
验证签名的准确性不应该pop掉sign_type

### ISSUE THREAD

**Issue by corleytd** [fzlee/alipay#111]
大佬，你好，我在测试这个SDK的时候发现了一个问题，在调用AliPay对象的verify方法的时候不应该pop掉sign_type，因为它也要参加签名过程，否则验证签名会一直不正确，给出修改参考的参考建议
```python
    def verify(self, data, signature):
        if "sign_type" in data:
            sign_type = data.get("sign_type", None)
            if sign_type != self._sign_type:
                raise AliPayException(None, "Unknown sign type: {}".format(sign_type))
        # 排序后的字符串
        unsigned_items = self._ordered_data(data)
        message = "&".join(u"{}={}".format(k, v) for k, v in unsigned_items)
        return self._verify(message, signature)
```

**Comment by fzlee** [comment]
你是哪一个接口验证失败的? pop sign_type 是故意做的, 因为sign_type 确实不应该参与签名验证

**Comment by fzlee** [comment]
参见这个文档:
https://opendocs.alipay.com/open/58/103596

**Comment by corleytd** [comment]
alipay.trade.page.pay(统一收单下单并支付页面接口)，必须要修改之后才能验证成功，否则一直失败，


官网https://opendocs.alipay.com/open/291/sign说了生成签名需要包括sign_type，我这里说的是验签，就是调用verify()方法，我看到源码是把sign_type给pop掉了，因此改过后验签就成功了，不知道其他接口什么情况，目前就这一个接口。



，必须要

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fzlee"<notifications@github.com&gt;; 
发送时间: 2020年8月2日(星期天) 上午10:38
收件人: "fzlee/alipay"<alipay@noreply.github.com&gt;; 
抄送: "P.k. ."<2920389388@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fzlee/alipay] 验证签名的准确性不应该pop掉sign_type (#111)





 
你是哪一个接口验证失败的? pop sign_type 是故意做的, 因为sign_type 确实不应该参与签名验证

**Comment by fzlee** [comment]
我想请问一下, 修改之后验证成功你指的是修改了这个库的源代码, 之后就可以通过签名验证吗?

我给你的链接是支付宝官方文档里面关于签名验证机制的. 按照道理不应该需要sign_type

**Comment by corleytd** [comment]
可以加一个微信或者QQ聊吗？这样发邮件不太方便。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 中午11:04
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"P.k. ."<2920389388@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] 验证签名的准确性不应该pop掉sign_type (#111)





 
我想请问一下, 修改之后验证成功你指的是修改了这个库的源代码, 之后就可以通过签名验证吗?
 
我给你的链接是支付宝官方文档里面关于签名验证机制的. 按照道理不应该需要sign_type

**Comment by fzlee** [comment]
尽量在这边留言吧, 有些信息希望让其他人看见

**Comment by fzlee** [comment]
验签的步骤里面, https://opendocs.alipay.com/open/291/106097 也提到了需要移除sign_type

**Comment by corleytd** [comment]
是的，下载了2.0.1的版本测试不行，然后今天刚刚发现2.1.0的版本更新了之后重新测试，还是不行，然后看源码发现sign_type被pop掉了，我就改成了只是get而不是pop，然后验证就成功了




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 中午11:10
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"P.k. ."<2920389388@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] 验证签名的准确性不应该pop掉sign_type (#111)





 
尽量在这边留言吧, 有些信息希望让其他人看见

**Comment by fzlee** [comment]
这个库从一开始就是pop sign_type, 你有时间发代码和报错信息上来看看吧

**Comment by corleytd** [comment]
验签其实就是把返回数据中的sign去掉，重新生成sign，将这个sign与获取到的sign对比，相同则成功，意思也就是需要生成sign，这就必须要sign_type，如下：

而你发的链接中


验签的参数中也是包含sign_type的。


我的代码并没有报错，只是验签一直不能返回True，返回的是False




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 中午11:13
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"P.k. ."<2920389388@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] 验证签名的准确性不应该pop掉sign_type (#111)





 
验签的步骤里面, https://opendocs.alipay.com/open/291/106097 也提到了需要移除sign_type

**Comment by fzlee** [comment]
你看看我发的链接中的图片, 验签步骤

![](http://mdn.alipayobjects.com/afts/img/A*J9hrQ4J7TTsAAAAAAAAAAABkAa8wAA/original?bz=openpt_doc&t=GKLPTyFRDrS4imNNpjW96wAAAABkMK8AAAAA)

**Comment by fzlee** [comment]
你要不下载支付宝的这个支付宝的开发助手, 使用我的这个库创建请求, 将开发助手和我这个库的输出做一个比较, 看看哪里不一致

**Comment by corleytd** [comment]
也可以，我先试试吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 中午11:28
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"P.k. ."<2920389388@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] 验证签名的准确性不应该pop掉sign_type (#111)





 
你要不下载支付宝的这个支付宝的开发助手, 使用我的这个库创建请求, 将开发助手和我这个库的输出做一个比较, 看看哪里不一致

**Comment by lzjun567** [comment]
我发现，pop 或者不 pop sign_type  调用 verify 的时候 都是返回 False

**Comment by lzjun567** [comment]
https://opendocs.alipay.com/open/200/106120

在通知返回参数列表中，除去sign、sign_type两个参数外，凡是通知返回回来的参数皆是待验签的参数。

说明：生活号异步通知组成的待验签串里需要保留sign_type参数。

**Comment by juran1993** [comment]
python-alipay-sdk  2.1.1
Django             2.2

在调用verify方法，如果pop掉sign_type，一直返回false  改成sign_type = data.get("sign_type", None)，就通过了

**Comment by juran1993** [comment]
success = alipay.verify(data, signature)

**Comment by fzlee** [comment]
我的意思是请问你使用的是手机支付， 还是什么其他的支付接口的时候， 验证不能pop掉sign type

**Comment by juran1993** [comment]
电脑网页支付

**Comment by fzlee** [comment]
3.0 版本不会自动pop任何数据， 请自己处理需要签名的字符串
