### ISSUE TITLE
app支付接口

### ISSUE THREAD

**Issue by smallzhuzhu** [fzlee/alipay#117]
你好，app支付接口中return-url无法设置啊，如果直接在notify-url后面添加的话会直接会将return-url加入bizContent参数中吧，这样好像不是适合的，有什么方法能直接设置吗。我试过在接口调完之后手动添加，支付宝中显示参数错误，求解

**Comment by fzlee** [comment]
你好， app支付目前确实是没有办法设置return url。
好奇为啥app支付需要用到return url？

**Comment by smallzhuzhu** [comment]
支付后不跳转回自己的app吗，不过我前端对接的同事改了点东西，好像传不传都能跳回来


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 下午5:36
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"小曹"<240586493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] app支付接口 (#117)





 
你好， app支付目前确实是没有办法设置return url。
 好奇为啥app支付需要用到return url？

**Comment by fzlee** [comment]
我怎么感觉应该是默认跳转回来的。。。并不是通过这个return url

**Comment by smallzhuzhu** [comment]
我也感觉是，因为一开始设置的时候我断点进去，return-url到bizcontent里面去了，这样是肯定不行的，我就一只以为是我服务端的东西没设置好，然后前端同事说好像是他那边配错了，我服务端传不传这个参数都能跳回去，我一开始想着这个return-url是跳转的，没啥用的话，估计只能用在电脑网站支付后的跳转了。你的包比官方的好用多了，官方的没有公钥证书模式，对接了半天才发现。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fzlee/alipay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 下午5:44
收件人:&nbsp;"fzlee/alipay"<alipay@noreply.github.com&gt;;
抄送:&nbsp;"小曹"<240586493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fzlee/alipay] app支付接口 (#117)





 
我怎么感觉应该是默认跳转回来的。。。并不是通过这个return url
