### ISSUE TITLE
证书签名里的*_key_string和*_cert_string是证书地址还是证书字符串?

### ISSUE THREAD

**Issue by jiancong952** [fzlee/alipay#119]
dc_alipay = DCAliPay(
    appid="appid",
    app_notify_url="http://example.com/app_notify_url",
    app_private_key_string=app_private_key_string,
    app_public_key_cert_string=app_public_key_cert_string,
    alipay_public_key_cert_string=alipay_public_key_cert_string,
    alipay_root_cert_string=alipay_root_cert_string
)

**Comment by fzlee** [comment]
key_string 都是证书字符串
