### ISSUE TITLE
web支付也有编码问题

### ISSUE THREAD

**Issue by openpython** [fzlee/alipay#13]
如下：
order_string = alipay.create_web_trade(out_trade_no=o.order_no, total_amount=str(o.total_fee), subject=o.subject,  return_url="http://pay.xxxx.com/alipay/sz_return_result/")
  File "/usr/local/lib/python2.7/dist-packages/alipay/__init__.py", line 206, in create_web_trade
    "&sign_type=" + self.__sign_type
  File "/usr/local/lib/python2.7/dist-packages/alipay/__init__.py", line 209, in _sign_data
    sign = self._sign_data_with_private_key(data, private_key_path)
  File "/usr/local/lib/python2.7/dist-packages/alipay/__init__.py", line 138, in _sign_data_with_private_key
    unsigned_string = "&".join("{}={}".format(k, v) for k, v in unsigned_items)
  File "/usr/local/lib/python2.7/dist-packages/alipay/__init__.py", line 138, in <genexpr>
    unsigned_string = "&".join("{}={}".format(k, v) for k, v in unsigned_items)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

**Comment by fzlee** [comment]
0.6.7已经修复这个问题

**Comment by openpython** [comment]
已更新至0.6.7，错误提示还一样

**Comment by fzlee** [comment]
可以贴一下你的代码吗？ 如果安装了requete， 可以贴上你的request版本号吗？

**Comment by openpython** [comment]
requests-2.12.3
部分代码：
`    o=Order.query.filter(Order.id==oid,Order.user_id==uid).first()
    if not o:
        return redirect(url_for('frontend.common_error', err_code=502))
    
    # 即时到帐，需要跳转到https://mapi.alipay.com/gateway.do? + order_string
    order_string = alipay.create_web_trade(out_trade_no=o.order_no, total_amount=str(o.total_fee), subject=o.subject, extra_common_param='mmdqfs|mjhcq8', return_url="http://pay.xxxx.com/alipay/return_result/")    
    
    return redirect('https://mapi.alipay.com/gateway.do?%s' % order_string)`

**Comment by fzlee** [comment]
你这边运行一下 type(o.subject)， 是unicode还是str对象？

**Comment by openpython** [comment]
检测是 <type 'unicode'>

**Comment by fzlee** [comment]
subject=o.subject.encode("utf-8") 应该可以暂时解决问题。你可以试一下
====
目前似乎我这边需要规范一下传入的字符串的数据类型，比如不论python2 还是 python3，都需要为unicode

**Comment by openpython** [comment]
不报编码错误了，但是alipay.com提示集成错误：

> 调试错误，请回到请求来源地，重新发起请求。
> 错误代码 ILLEGAL_SIGN

这可能是哪里的问题呢？

**Comment by fzlee** [comment]
签名错误，你先确认一下自己使用的签名私钥，它对应的公钥传给了支付宝
