### ISSUE TITLE
添加支持 alipay.fund.account.query(支付宝资金账户资产查询接口)

### ISSUE THREAD

**Issue by lch277** [fzlee/alipay#136]
**Describe the problem**
正在开发转账到支付宝帐号的功能，需要调用账户资产查询接口确认余额，sdk没找到该接口的调用方式

**Environment**
OS version:
Python version:
Alipay version: 3.0.4

**To reproduce**
Code snippets:
```python
alipay = Alipay(...)
alipay.do_something
```

**Expected behavior **

**Comment by fzlee** [comment]
你可以试试新版的 client_api

**Comment by lch277** [comment]
搞定了，谢谢
