### ISSUE TITLE
alipay.api_alipay_trade_query(out_trade_no=order_id)

### ISSUE THREAD

**Issue by jackwu882002** [fzlee/alipay#137]
**Describe the problem**
您好，请问以前文档中是有 这个查询支付的功能说明，现在好像文档中找不到这个说明了，请问是合并了？还是有什么更新呢？
我想主动去查询 订单 是否支付成功，麻烦解疑一下，谢谢了。
**Environment**
OS version:
Python version:
Alipay version:

**To reproduce**
Code snippets:
```python
alipay = Alipay(...)
alipay.do_something
```

**Expected behavior **

**Comment by fzlee** [comment]
https://github.com/fzlee/alipay/blob/master/docs/apis.zh-hans.md

**Comment by fzlee** [comment]
你指的是这个？

因为发现支付宝有很多支付接口，一个一个写不过来， 所以弄了一个统一的server_api 以及client_api, 可以覆盖大部分的使用场景

**Comment by jackwu882002** [comment]
我仔细又看了一次您的文档。发现 把 交易预创建、交易查询和交易取消 ，文档排版 时候放在 同一个部分，还以为是 没有了交易查询和取消部分，谢谢了。


交易预创建(扫码支付) alipay.trade.precreate
alipay = AliPay(appid="", ...)

# create an order
alipay.api_alipay_trade_precreate    (
    subject="test subject",
    out_trade_no="out_trade_no",
    total_amount=100
)

# check order status
paid = False
for i in range(10):
    # check every 3s, and 10 times in all
    print("now sleep 3s")
    time.sleep(3)
    result = alipay.api_alipay_trade_query(out_trade_no="out_trade_no")
    if result.get("trade_status", "") == "TRADE_SUCCESS":
        paid = True
        break
    print("not paid...")

# order is not paid in 30s , cancel this order
if paid is False:
    alipay.api_alipay_trade_cancel(out_trade_no=out_trade_no)

我想应该是可以用的，我测试一下，谢谢。

**Comment by jackwu882002** [comment]
可以正常使用 谢谢
