### ISSUE TITLE
uwsgi 无法正常返回

### ISSUE THREAD

**Issue by jackwu882002** [fzlee/alipay#138]
**Describe the problem**
在测试时候 uwsgi 是呀http的端口 是可以正常支付宝，但是 Django中 Nginx和uwsgi配合使用 用scoket，就无法正常支付宝宝，请问如何处理么，谢谢。app alipay

**Environment**
OS version:
Python version:
Alipay version:

**To reproduce**
Code snippets:
```python
alipay = Alipay(...)
alipay.do_something
```

**Expected behavior **

**Comment by jackwu882002** [comment]
Describe the problem
在测试时候 uwsgi 是使用http的端口 是可以正常支付宝，但是 Django中 Nginx和uwsgi配合使用 用socket，就无法正常支付宝宝，请问如何处理么，谢谢。app alipay

Environment

**Comment by jackwu882002** [comment]
app_private_key_string = open("/path/to/your/private/key.pem").read()
alipay_public_key_string = open("/path/to/alipay/public/key.pem").read()

我测试以后 用http 初始化 正确,没有问题. 但是 直接用Nginx和uwsgi的socket,初始化就报错,请问知道为啥这个问题,如何处理呢？

**Comment by fzlee** [comment]
直接用Nginx和uwsgi的socket,初始化就报错
请问报什么错呢

**Comment by jackwu882002** [comment]
> 我设置了测试点，当 我只是用 uwsgi http ：8001 去启动服务器，可以使用 支付宝支付；但是 用nginx和uwsgi 启动 服务器以后，我设置的测试点，发现 第一步就失败了，在设置 初始化的 公匙和私钥 就失败了，无法运行，我用的是Django 在SDK开始初始化的阶段就失败了。非常奇怪。我觉得其中的差异 就是 uwsgi用http，用nginx时候用socket的差别，但是，我觉得这个问题，应该没有问题才对，请大神给予指导，感谢。

**Comment by fzlee** [comment]
这个问题看起来跟这个库无关。
作为一个调试方法，你可以试试在代码里面将证书作为字符串嵌入代码。应该会正常运行
