### ISSUE TITLE
您好，请问支持分账吗？

### ISSUE THREAD

**Issue by wuqiang-001** [fzlee/alipay#147]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wuqiang-001** [comment]
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/85499933/222896638-fbb04444-106c-4eec-9329-281c8bf5c6c4.png">

**Comment by fzlee** [comment]
你可以试试server_api这个接口，理论上大部分支付宝接口都可以通过server_api和client_api实现

**Comment by fzlee** [comment]
https://github.com/fzlee/alipay/blob/master/docs/apis_new.md

**Comment by wuqiang-001** [comment]
好的，我试一下，有问题再请教您

**Comment by fzlee** [comment]
https://github.com/fzlee/alipay/blob/master/docs/apis.zh-hans.md#alipay.trade.close

**Comment by fzlee** [comment]
这里好像有的

**Comment by wuqiang-001** [comment]
您好，服务商进件支持吗?

**Comment by fzlee** [comment]
有文档吗

**Comment by wuqiang-001** [comment]
https://opendocs.alipay.com/pre-apis/0282hf 这是地址
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/85499933/223037010-61a80b52-2334-4c4d-a5a9-a5fdb1b51917.png">

**Comment by fzlee** [comment]
你试试ISVAlipay + server_api/client_api, 理论上是支持的

**Comment by fzlee** [comment]
> https://opendocs.alipay.com/pre-apis/0282hf 这是地址 <img alt="image" width="1178" src="https://user-images.githubusercontent.com/85499933/223037010-61a80b52-2334-4c4d-a5a9-a5fdb1b51917.png">

请问isvalipay, server_api 可以解决问题吗
