### ISSUE TITLE
应用网关是什么

### ISSUE THREAD

**Issue by beimusky** [fzlee/alipay#150]
在支付宝后台中，看到有一个应用网关的设置
用于接收支付宝异步通知消息（例如[From平台消息](https://opendocs.alipay.com/common/02km9j)等），需要传入http(s)公网可访问的网页地址。选填，若不设置，则无法接收相应的异步通知消息
请问这个包内是否有相应接口来对应，支付宝的这个东西应用场景是啥

**Comment by fzlee** [comment]
1. 支持，参见“通知验证”
2. 应用场景是订单被支付之后支付宝通知你

**Comment by beimusky** [comment]
> 1. 支持，参见“通知验证”
> 2. 应用场景是订单被支付之后支付宝通知你

创建对象时 那不是还有一个 app_notify_url 吗，有啥不同？

**Comment by fzlee** [comment]
app_notify_url 还有应用网关应该都可以用做消息推送。

例如[From平台消息](https://opendocs.alipay.com/common/02km9j)等 => 应用网关的用途应该比app_notify_url 更加广。
app_notify_url应该是在向支付宝发器支付申请的时候， 指明支付宝回调到哪里。
但是有一类操作并不是因为支付行为才产生的， 这时候应用网关会更加合适一点。


下面的说法你可以帮忙验证一下， 隐隐约约有这个印象， 不确定了。
====
如果支付申请里面没有包含app_notify_url.  消息会被推送到应用网关？
