### ISSUE TITLE
notify 回调消息验证失败 binascii.Error: Invalid base64-encoded string

### ISSUE THREAD

**Issue by lifeiteng** [fzlee/alipay#154]
**Describe the bug**
```
  File "..... payment.py", line 158, in verify
    success = self.alipay_gateway.verify(message, signature)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alipay/__init__.py", line 206, in verify
    return self._verify(message, signature)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/alipay/__init__.py", line 196, in _verify
    return bool(signer.verify(digest, decodebytes(signature.encode())))
  File "/usr/lib/python3.10/base64.py", line 562, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (357) cannot be 1 more than a multiple of 4

```

消息内容

'gmt_create=2023-09-10+22%3A46%3A18&charset=utf-8&gmt_payment=2023-09-10+22%3A46%3A24&notify_time=2023-09-10+22%3A46%3A24&subject=Creater+%E8%AE%A2%E9%98%85&sign=iwv9449sY2Zm%2BtEcOzQ01bK8p1ZlAqR8NASJxZ3crgnK%2BUpOZ6R4xybuDbZ90vpcvGVOj1p82a3u%2FYK9y6bS8m6eLLksv6PNHU8CZTMtg6y720YdUTfI8pJJH027rwwDAk53HAKj6KPnvrWWy8GBc0TaK5aYDjkI1wTtssgRcr65V%2Fvim9ro58qxuZh981r1KCzDj%2BFNKXy%2FiA%2BwQjNs1UwDivxeppFkPZvdvE9GNX7eBZBhj%2Fyof025NAgJKMNrJB2iM3gHHyexNOLtJvdmmqLbMKtpXS874S%2FYGK2qnQRkYLH9gCsG2raXjQnrXsA0cNt%2BAcgBDTBRSJJyTgEX%2Bw%3D%3D&merchant_app_id=2021004113680090&buyer_open_id=005XXk5k4SyYzOrYCht_waHgZJyHcXohSilRjm4RVEUyXsc&invoice_amount=2.00&version=1.0&notify_id=2023091001222224624039051458135489&fund_bill_list=%5B%7B%22amount%22%3A%222.00%22%2C%22fundChannel%22%3A%22ALIPAYACCOUNT%22%7D%5D&notify_type=trade_status_sync&out_trade_no=20230910_22_bd6e08621a2f7fb5ba87&total_amount=2.00&trade_status=TRADE_SUCCESS&trade_no=2023091022001439051412400253&auth_app_id=2021004113680090&receipt_amount=2.00&point_amount=0.00&buyer_pay_amount=2.00&app_id=2021004113680090&sign_type=RSA2&seller_id=2088641875615595'

```
 {'gmt_create': '2023-09-10+22%3A46%3A18', 'charset': 'utf-8', 'gmt_payment': '2023-09-10+22%3A46%3A24', 'notify_time': '2023-09-10+22%3A46%3A24', 'subject': 'Creater+%E8%AE%A2%E9%98%85', 'sign': 'iwv9449sY2Zm%2BtEcOzQ01bK8p1ZlAqR8NASJxZ3crgnK%2BUpOZ6R4xybuDbZ90vpcvGVOj1p82a3u%2FYK9y6bS8m6eLLksv6PNHU8CZTMtg6y720YdUTfI8pJJH027rwwDAk53HAKj6KPnvrWWy8GBc0TaK5aYDjkI1wTtssgRcr65V%2Fvim9ro58qxuZh981r1KCzDj%2BFNKXy%2FiA%2BwQjNs1UwDivxeppFkPZvdvE9GNX7eBZBhj%2Fyof025NAgJKMNrJB2iM3gHHyexNOLtJvdmmqLbMKtpXS874S%2FYGK2qnQRkYLH9gCsG2raXjQnrXsA0cNt%2BAcgBDTBRSJJyTgEX%2Bw%3D%3D', 'merchant_app_id': '2021004113680090', 'buyer_open_id': '005XXk5k4SyYzOrYCht_waHgZJyHcXohSilRjm4RVEUyXsc', 'invoice_amount': '2.00', 'version': '1.0', 'notify_id': '2023091001222224624039051458135489', 'fund_bill_list': '%5B%7B%22amount%22%3A%222.00%22%2C%22fundChannel%22%3A%22ALIPAYACCOUNT%22%7D%5D', 'notify_type': 'trade_status_sync', 'out_trade_no': '20230910_22_bd6e08621a2f7fb5ba87', 'total_amount': '2.00', 'trade_status': 'TRADE_SUCCESS', 'trade_no': '2023091022001439051412400253', 'auth_app_id': '2021004113680090', 'receipt_amount': '2.00', 'point_amount': '0.00', 'buyer_pay_amount': '2.00', 'app_id': '2021004113680090', 'sign_type': 'RSA2', 'seller_id': '2088641875615595'}
```

**Comment by lifeiteng** [comment]
是不是应该转码一遍 UTF-8 到 ASCII？
https://www.w3school.com.cn/tags/html_ref_urlencode.asp

**Comment by lifeiteng** [comment]
根据 https://github.com/alipay/alipay-sdk-python-all/blob/master/alipay/aop/api/util/WebUtils.py#L109

```
try:
    from urllib.parse import unquote_plus
except ImportError:
    from urllib import unquote_plus

message = {
    item[0]: unquote_plus(item[1])
    for item in [
        field.split("=") for field in raw_body.decode("utf-8").split("&")
    ]
}
```

**Comment by fzlee** [comment]
这个问题看表象应该是你证书短了一些导致的

**Comment by lifeiteng** [comment]
> 这个问题看表象应该是你证书短了一些导致的

不是的，我上面的代码片段修复了；是字符编码的问题 `'gmt_create': '2023-09-10+22%3A46%3A18',` -> `'gmt_create': unquote_plus('2023-09-10+22%3A46%3A18'),`

**Comment by lifeiteng** [comment]
我没找到把消息 body 转成字典的接口，自己写了转换逻辑
```
message = {
    item[0]: unquote_plus(item[1])
    for item in [
        field.split("=") for field in raw_body.decode("utf-8").split("&")
    ]
}
```

**Comment by fzlee** [comment]
@lifeiteng 你好， 为了方便其他人不会遇到这个问题，我确认一下。 
1. 你用的是什么后端框架？
2. 你调用verify的时候， 传入的参数是这样的吗
 ```python
success = self.alipay_gateway.verify(message, signature)

这是你的message
message =  {{'gmt_create': '2023-09-10+22%3A46%3A18', 'charset': 'utf-8', 'gmt_payment': '2023-09-10+22%3A46%3A24' ...}
而实际上你认为正确的应该是这样的：

message =  {{'gmt_create': '2023-09-10+22:46:18', 'charset': 'utf-8', 'gmt_payment': '2023-09-10+22:46:24' ...}

```

**Comment by lifeiteng** [comment]
@fzlee fastapi

**Comment by fzlee** [comment]
你看一下这个链接

https://stackoverflow.com/questions/67393319/getting-query-parameters-as-dictionary-in-fastapi

将query里面的参数转化成dict是你这边应该做的。

你说的对，传入verify函数的参数应该是被unquote的， 但是我这边不会做这个转换。
