### ISSUE TITLE
The api_alipay_trade_precreate get error

### ISSUE THREAD

**Issue by honghh2018** [fzlee/alipay#160]
你好，开发者，
   我通过python的 upgrate安装的 sdk 
   
   代码：
   class AliPay2(object):
    def __init__(self, appid, ali_pay_gateway, app_private_key_path, alipay_public_key_path):
        self.app_private_key_path = app_private_key_path
      
        with open(self.app_private_key_path) as fp:
            self.app_private_key =  fp.read()

        self.alipay_public_key_path = alipay_public_key_path
        with open(self.alipay_public_key_path) as fp:
            self.alipay_public_key =  fp.read()

   
        self.alipay = AliPay(
            appid=appid,
            app_notify_url=None,  # 默认回调 url
            # app_private_key_string=self.app_private_key,
            # 
            app_private_key_string=self.app_private_key,
            # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
            # alipay_public_key_string=self.alipay_public_key,
            # 
            alipay_public_key_string=self.alipay_public_key,
            sign_type="RSA2",  # RSA 或者 RSA2   # 必须选项设置为RSA2
            debug=True,  # 默认 False  # 使用沙箱环境
            verbose=False,  # 输出调试数据
            config=config  # 可选，请求超时时间
        )

    def direct_pay(self):
        # out_trade_no = str(int(time.time()))   # 字符串和整数都试过，报一样的错 40004    交易不存在
        out_trade_no = int(time.time())
        # create an order
        self.alipay.api_alipay_trade_precreate(
            subject="云平台工具",
            out_trade_no=out_trade_no,
            total_amount=10
        )

        # check order status #
        paid = False
        for i in range(3):
            # check every 3s, and 10 times in all
            print("now sleep 3s")
            time.sleep(3)
            result = self.alipay.api_alipay_trade_query(out_trade_no=out_trade_no)
            print("result-->",result)
            if result.get("trade_status", "") == "TRADE_SUCCESS":
                paid = True
                break
            print("not paid...")

        # order is not paid in 30s , cancel this order
        if paid is False:
            self.alipay.api_alipay_trade_cancel(out_trade_no=out_trade_no)
   
   通过沙箱环境测试的，一直报错如下：
  
    {'msg': 'Business Failed', 'code': '40004', 'out_trade_no': '1731225211', 'sub_msg': '交易不存在', 'sub_code': 'ACQ.TRADE_NOT_EXIST', 'receipt_amount': '0.00', 'point_amount': '0.00', 'buyer_pay_amount': '0.00', 'invoice_amount': '0.00'}
    
    如何解决这个问题呢？
    有什么建议会非常感谢
    hanhuihong

**Comment by fzlee** [comment]
你需要把api_alipay_trade_precreate 的返回打印出来， 使用支付宝扫码， 订单状态才会变化
