### ISSUE TITLE
php 调用/v3/alipay/trade/precreate时响应状态是200，但是没有看到二维码相关信息

### ISSUE THREAD

**Issue by lilipengone** [fzlee/alipay#161]
代码：
 $api = $this->createApi();
        $aliRequest = new AlipayTradePrecreateModel();
        $aliRequest->setOutTradeNo($trade_no);
        $aliRequest->setTotalAmount($price);
        $aliRequest->setSubject($trade_no);
        $aliRequest->setNotifyUrl($notifyUrl);

        $aliResponse = $api->precreate($aliRequest);
        // 获取收款二维码内容
        $qrCode = $aliResponse->getQrCode();

        return $response->withJson([
            'ret' => 1,
            'qrcode' => $qrCode,
            'pid' => $trade_no,
        ]);

日志：
[INFO] 2024-12-07 08:31:41^_^PHP_OS:Linux^_^PHP_VERSION:8.2.22^_^url:https://openapi.alipay.com/gateway.do/v3/alipay/trade/precreate^_^method:POST^_^requestId:917b65bd-c5a0-7850-4710-a3caba061153^_^contentType:application/json^_^body:{"notify_url":"https:\/\/ip\/payment\/notify\/f2f","out_trade_no":"3611a099","subject":"3611a099","total_amount":"1"}

 [INFO] 2024-12-07 08:31:42^_^PHP_OS:Linux^_^PHP_VERSION:8.2.22^_^HTTP **response code:200**^_^HTTP response body:^_^HTTP response headers:{"Date":["Sat, 07 Dec 2024 00:31:42 GMT"],"Content-Type":["text\/html;charset=GBK"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"Server":["spanner\/1.6.2"],"Vary":["Accept-Encoding"],"trace_id":["21932e4917335315020956997e508a"],"Set-Cookie":["zone=RZ42A; Domain=.alipay.com; Path=\/","JSESSIONID=DD9B52388D735CA15DD43F4617821E8F; Path=\/; HttpOnly","JSESSIONID=DD9B52388D735CA15DD43F4617821E8F; Path=; HttpOnly","ALIPAYJSESSIONID=RZ42WqrQOSBJ1rFmHCepbmZLXuKfn8authRZ42; Domain=.alipay.com; Path=\/","ctoken=vuf08MDOYtx1iSkV; Domain=.alipay.com; Path=\/","umt=L9032537ddc196e78aca612ceca81071f; Domain=.alipay.com; Path=\/; HttpOnly","auth_goto_http_type=empty; Domain=.alipay.com; Expires=Sat, 07-Dec-2024 01:01:42 GMT; Path=\/; Secure; HttpOnly; SameSite=None","spanner=n0GzQVrrw+umOBRN1xjteczDvMu\/5XCX;path=\/;secure;","spanner_proxy=do7OuyYrG6TBX8DpqbudpCuSU9wlT\/DZ4EJoL7C0n0A=;path=\/;secure;"],"Strict-Transport-Security":["max-age=31536000"],"Content-Language":["zh-CN"],"Via":["spanner-internet-cz20k-78.et2[200], ispanner-internet-pot-sggz00e-7.sg113x[200]"],"Origin-Agent-Cluster":["?0"]}

**Comment by fzlee** [comment]
额， 我这个是python的库

**Comment by lilipengone** [comment]
额。。。不好意思，选错库了
