### ISSUE TITLE
加回调参数passback_params不起作用。

### ISSUE THREAD

**Issue by kingctan** [fzlee/alipay#17]
加回调参数passback_params不起作用。

**Comment by fzlee** [comment]
请问是哪一个接口？

**Comment by kingctan** [comment]
alipay.trade.page.pay

**Comment by fzlee** [comment]
我尝试了一次，确实有返回passback_params的。你可以把具体的流程贴上来，看看有什么问题

**Comment by kingctan** [comment]
难道我传参不对么？请看一下我的传参有什么问题么？
···
urlparams = alipay.api_alipay_trade_page_pay(order['GroupTitle'], order['SysOrderNo'], order['FeeAmt'],passback_params='feecode=%s' % (order['FeeCode'],))
···

**Comment by fzlee** [comment]
你试试这个：
urlparams = alipay.api_alipay_trade_page_pay(order['GroupTitle'], order['SysOrderNo'], order['FeeAmt'],passback_params=quote_plus("feecode=123456"),))

passback_params 需要转义，
然后你应该就可以在异步回调的通知里面，看到这个参数了

**Comment by kingctan** [comment]
谢谢！
alipay.trade.page.pay  这个可以了。
但这个：alipay.trade.precreate，接不到回调了。

**Comment by kingctan** [comment]
方便加一下你QQ么？^_^

**Comment by fzlee** [comment]
你可以确认一下precreate是否有回调通知， 可能需要你轮询获取支付状态。
