### ISSUE TITLE
调试不过

### ISSUE THREAD

**Issue by alaikis** [fzlee/alipay#24]
你好，调试不过，是否可以发邮件给我，alex@laialex.com,涉及隐私信息，邮件比较好

**Comment by fzlee** [comment]
你可以贴上一个可以复现错误的简单代码，并且提供你的一些环境变量， 比如python版本，操作系统等等。

抱歉不能和你邮件联系。 我感觉你把错误信息贴到这里，可以让其他人看到，顺便帮助遇到同样问题的人

**Comment by fzlee** [comment]
如果涉及隐私信息，移除掉那部份隐私信息就好
