### ISSUE TITLE
有没有写支付宝小程序的方法

### ISSUE THREAD

**Issue by zhilangtaosha** [fzlee/alipay#25]
现在在开发支付宝小程序，只想获得用户信息，却不知道如何下手

**Comment by fzlee** [comment]
微信这货的小程序到现在还是不温不火的，支付宝的估计更难火了。这个项目暂时不提供小程序的接口

**Comment by zhilangtaosha** [comment]
最近在参加支付宝的小程序开发者大赛，对小程序的开发还有前端机制一律不熟，只会一点点python，还是希望大神能考虑一下小程序，他的生态系统比微信的好很多。

**Comment by fzlee** [comment]
我看了看支付宝小程序的后端接口，实现起来并不难，因为核心的签名算法我这个库已经提供了， 你仿照源代码里面的函数，自己添加几个新的接口就好了。

**Comment by zhilangtaosha** [comment]
是的，我感觉也不难，就是这个机制摸了两天了也搞不懂什么意思，隔行的悲伤
