### ISSUE TITLE
交易预创建收不到异步消息

### ISSUE THREAD

**Issue by 109ta** [fzlee/alipay#30]
我在Alipay创建实例时设置了app_notify_url，但测试多次都未收到支付宝的异步通知，后来发现是由于代码在build_body方法if method in ()中未考虑"alipay.trade.precreate"的情况，所以新开了个issue，以便后面和我遇到同一情况的人可以参考一下。
![2017-11-15 10 16 44](https://user-images.githubusercontent.com/7339593/32815412-f41870ae-c9ee-11e7-89b6-79db82ca3119.png)

**Comment by Macuilxochitl** [comment]
现在已经有了
