### ISSUE TITLE
出现加密错误

### ISSUE THREAD

**Issue by alaikis** [fzlee/alipay#32]
![image](https://user-images.githubusercontent.com/30462479/33003623-c79f6e36-cdf6-11e7-95f4-fa6cf4c3570b.png)

**Comment by fzlee** [comment]
可以输出你初始化Alipay用到的参数， 以及你调用api_alipay_trade_page_pay 用到的参数吗？

**Comment by alaikis** [comment]
appid:2017101009227809
app_notify_url:https://api.quidci.com/v1/alipy/callback
app_private_key_path:/home/developer/quidci/lib/zfb/rsa/private.pem
alipay_public_key_path:/home/developer/quidci/lib/zfb/rsa/alipay.pem
sign_type:RSA2
------------------- init atttri ------------------------
subject:201711201139453960用户在线充值
out_trade_no:201711201139453960
total_amount:5
--------------------webpay attri------------------------

**Comment by fzlee** [comment]
我本地测试是没有问题的。
报错的原因可能是一些特殊的对象，比如None传递给了quote_plus函数导致的。

====

1. 建议手动修改上面截图里面的源代码，也就是/home/webapps/..../site-packages/alipay/__init__.py ， 242行，print(data), 看看到底传了哪些参数给sign_data这个函数。
2. 或者是155行，print(ordered_items).

**Comment by alaikis** [comment]
[('app_id', 2017101009227809), ('biz_content', '{"subject":"201711201201172360\\u7528\\u6237\\u5728\\u7ebf\\u5145\\u503c","out_trade_no":"201711201201172360","total_amount":"5","product_code":"FAST_INSTANT_TRADE_PAY"}'), ('charset', 'utf-8'), ('method', 'alipay.trade.page.pay'), ('notify_url', 'https://api.quidci.com/v1/alipy/callback'), ('sign_type', 'RSA2'), ('timestamp', '2017-11-20 12:01:18'), ('version', '1.0')]

**Comment by fzlee** [comment]
appid 应该是一个字符串，你似乎传入了整数。

这个库应该支持将传入的整数转换为字符串，这个功能以后会实现。
