### ISSUE TITLE
是否可以不使用文件

### ISSUE THREAD

**Issue by alaikis** [fzlee/alipay#37]
你好，证书信息是否可以直接存数据库，而不是文件，这样多用户时比较好处理，谢谢

**Comment by alaikis** [comment]
就是在初始化时直接传入证书信息，不是传入文件路径

**Comment by fzlee** [comment]
可以的，我下周加入这个功能

**Comment by fzlee** [comment]
1.6已经上传， 有空帮我测测吧

**Comment by alaikis** [comment]
你好，PIP包才1.5.1，更新一下

**Comment by fzlee** [comment]
你用的是中国的源吧，可能会有一些延迟

**Comment by alaikis** [comment]
证书字符串需不需要加上-----BEGIN PUBLIC KEY-----之类的并分行，还是原始的支付宝公匙就好，

**Comment by fzlee** [comment]
需要的

**Comment by alaikis** [comment]
ok评测没有任何问题，你最好在文档说明下支付宝公匙要自己格式化下，不然大家直接复制都用不了
