### ISSUE TITLE
即时到账有密退款接口没有或者alipay.refund_web_order方法不兼容即时到账支付宝接口

### ISSUE THREAD

**Issue by varwey** [fzlee/alipay#4]
即时到账退款的接口只有一个合作者身份ID，没有APPID，以及其余参数和refund_web_order也不同，接口走的是 `https://mapi.alipay.com/gateway.do `。即时到账接口文档：
[https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.LnFTM0&treeId=62&articleId=104744&docType=1](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.LnFTM0&treeId=62&articleId=104744&docType=1)

**Comment by fzlee** [comment]
即时到帐的退款可以用有密退款，就是你刚才提到的那个文档，需要你在网页输入密码确认才能退款。

也可以使用alipay.trade.refund (统一收单交易退款接口)。也就是我现在实现的那个接口，调用我的接口时，传入partner id就好，不需要appid，你可以试一试

**Comment by varwey** [comment]
对的，不过我们以前申请的支付宝开发平台应用只有一个合作者身份ID，我尝试将这个id传入（即partner id）不过还是有点问题。我提交一下，你看看是不是这个问题。
