### ISSUE TITLE
关于主页介绍中AliPay初始化的问题

### ISSUE THREAD

**Issue by xinlingqudongX** [fzlee/alipay#41]
在主页介绍中，app_notify_url设置为一个空的字符串，但是在实际测试中，如果不使用app_notify_url，那么一定要设置为None，不然就算是私钥和公钥设置好了，支付宝还是会提示验证签名失败

**Comment by fzlee** [comment]
稍微修改了一下文档， 下次有功能更新的时候会把空字符串妥善处理
