### ISSUE TITLE
使用api_alipay_trade_query的时候报错

### ISSUE THREAD

**Issue by PerryYuan** [fzlee/alipay#42]
======代码
@app.route('/check_pay/', methods=['POST'])
def check_pay():
    # 创建用于进行支付宝支付的工具对象
    order_id = flask.request.form.get("order_id")
    alipay = AliPay(
        appid=ALIPAY_APPID,
        app_notify_url=None,  # 默认回调url
        app_private_key_path=os.path.join(BASE_DIR, "malipay/app_private_key.pem"),
        alipay_public_key_path=os.path.join(BASE_DIR, "malipay/alipay_public_key.pem"),
        # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
        sign_type="RSA2",  # RSA2,官方推荐，配置公钥的时候能看到
        debug=True  # 默认False  配合沙箱模式使用
    )

    # raw_string = urlopen(url, timeout=15).read().decode("utf-8")
    while True:
        # 调用alipay工具查询支付结果
        response = alipay.api_alipay_trade_query(out_trade_no=order_id)  # response是一个字典
        # 判断支付结果
        code = response.get("code")  # 支付宝接口调用成功或者错误的标志
        trade_status = response.get("trade_status")  # 用户支付的情况

        if code == "10000" and trade_status == "TRADE_SUCCESS":
            # 表示用户支付成功
            # 返回前端json，通知支付成功
            return flask.jsonify({"code": 0, "message": "支付成功"})

        elif code == "40004" or (code == "10000" and trade_status == "WAIT_BUYER_PAY"):
            # 表示支付宝接口调用暂时失败，（支付宝的支付订单还未生成） 后者 等待用户支付
            # 继续查询
            print(code)
            print(trade_status)
            continue
        else:
            # 支付失败
            # 返回支付失败的通知
            return flask.jsonify({"code": 1, "message": "支付失败"})
=====
报错信息
raise ValueError("Not a valid PEM post boundary")
ValueError: Not a valid PEM post boundary

可以支付，但是不能查询。希望帮忙看下。

**Comment by fzlee** [comment]
Not a valid PEM post boundary 这个报错看起来像是证书格式有问题

**Comment by PerryYuan** [comment]
但是我可以支付哦。。

**Comment by fzlee** [comment]
创建支付使用的是你的密钥，查询的时候用到了支付宝的密钥， 应该是支付宝密钥格式不对

**Comment by PerryYuan** [comment]
使用支付宝的给的公钥吗？？
这个是支付宝的公钥：

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAykH+i0d3Bnjpls6+RLGgo26t6hXJ/0fHA4alWV2UiPmaKcyvJCVFVF06YhghxN4Gkt2IzMXRIimPg44jtEqvRfLZjUfMEKnn67zS/ONCUyJO42m6t2yRAPatqHJP0/3od3OfYKAXzQj+ONoFg84wqrm8lVQdllTl5DWFh60zrymIsuKh94RwHbcspa27cAeD+LGPV5AXVW0pFkK+jMOl0KgNCvH09Dr6eg4/OVL+Wq2Jh5y48B1nbb0viul0hpd2JkYC6SNN8N/IfCw5PgqzQtdqF4fpzQDMgCtWVv7SlQectaU5VKvCLjasSWf3iOHS0bMjs4rLi4GXqTCBH7arYwIDAQAB
-----END PUBLIC KEY----
这个是我在支付宝哪里复制下来的。。

**Comment by fzlee** [comment]
是用支付宝公钥没错， 但我感觉是不是里面有特殊字符串或者因为其他原因，导致读取这个公钥失败了

2018-04-03 11:19 GMT+08:00 PerryYuan <notifications@github.com>:

**Comment by PerryYuan** [comment]
重新复制了一下，还是不行呢。。

**Comment by fzlee** [comment]
https://github.com/fzlee/alipay/blob/master/tests/certs/ali/ali_public_key.pem
你参考一下上面的格式吧， 注意换行

2018-04-03 11:27 GMT+08:00 PerryYuan <notifications@github.com>:

**Comment by PerryYuan** [comment]
可以了。谢谢你啦。可能是在复制别人的---begin这些的时候用了中文换行。刚才，把那些删除了，重新写过就行了。。
