### ISSUE TITLE
请问交易预创建(扫码支付)有返回二维码地址吗？

### ISSUE THREAD

**Issue by bearllm** [fzlee/alipay#44]
官方文档返回是：
    "alipay_trade_precreate_response": {
        "code": "10000",
        "msg": "Success",
        "out_trade_no": "6823789339978248",
        "qr_code": "https://qr.alipay.com/bavh4wjlxf12tper3a"
    },
    "sign": "ERITJKEIJKJHKKKKKKKHJEREEEEEEEEEEE"
}

其中，qr_code用来生成二维码让客人扫码支付，我看咱们SDK的例程里面没有返回好像

我自己写的代码，“同步返回验签”总是通不过，不知 作者有么有时间帮忙指导下呢？

**Comment by fzlee** [comment]
1. 验证同步接口的返回， 建议参看源代码里面的 这个函数`_verify_and_return_sync_response`，里面有一个比较笨的验证同步接口的函数。

2. 交易预创建返回的是一个字符串，一般直接传给网页前端， 网页前端调用相应的库将字符串渲染成二维码。

**Comment by bearllm** [comment]
alipay = AliPay(appid="", ...)

# create an order
alipay.api_alipay_trade_precreate    (
    subject="test subject",
    out_trade_no="out_trade_no",
    total_amount=100
)

例程是这样的
您的意思是可以

rq_url=alipay.api_alipay_trade_precreate    (
    subject="test subject",
    out_trade_no="out_trade_no",
    total_amount=100
)

这样就得到了生成二维码的url么？

**Comment by fzlee** [comment]
你可以result = alipay.alipay.api_alipay_trade_precreate(xxxx)
然后print(result)
result其实是一个字典， 里面的内容是支付宝服务器返回的数据， 没有做过任何修改。
你要的二维码应该在result["qr_code"]里面

2018-04-23 18:09 GMT+08:00 bearllm <notifications@github.com>:

**Comment by bearllm** [comment]
这个我知道哈，我之前没有用SDK已经自己实现了的，只是看到例程里面没有这样写，觉得有些奇怪，不然不生成二维码这个接口无意义
