### ISSUE TITLE
同步验签

### ISSUE THREAD

**Issue by whmsysu** [fzlee/alipay#45]
抱歉实在麻烦作者了，有个问题想问一下,
如果app直接把支付宝返回的结果交给网站来做同步验签，请问能否使用这个sdk来完成。样例如下:

{'sign_type': 'RSA2', 'sign': 'Iril1rkvl7KUifMM0j7LyTgSMW/XnwnK7kVfVN42Gtvv+2dWpOUvEY8PEXavAldQIyL6YPg074BJema3s3ineer53X61AeXEPfnz6uHQHjDYSYf1AVn/uOfsCtRxdWRDlV4rPsf4ARTPlPf4rcTEcyTbsviPKi/dAvsN3mo1yBfZH2KX2qw6VGOAAqeinMLDf78reCWyp8KHPMBl1+iPDa2Bzg8l2U0rD5p/C+p+3Ou8tLHOEa0p+agjM11Z585yxctA/DdTgVgkPL0YeSv4zz6A/GAzmySzi61M5Clf/mXib3VdZrseObPNDW4hKtvfFXhIgU1egFdpbOZD7CCGIw==', 'alipay_trade_app_pay_response': {'charset': 'utf-8', 'msg': 'Success', 'seller_id': '2088821540881344', 'timestamp': '2018-04-24 01:48:58', 'out_trade_no': 'CO_322_0_1524505548', 'auth_app_id': '2017111409922946', 'code': '10000', 'trade_no': '2018042421001004700254850965', 'app_id': '2017111409922946', 'total_amount': '39.00'}}

读取了alipay_trade_app_pay_response是一个字典

**Comment by fzlee** [comment]
_verify_and_return_sync_response这个函数就是用来验证同步接口数据的
