### ISSUE TITLE
是否考虑像Django一样从2.0开始只支持python3？

### ISSUE THREAD

**Issue by waketzheng** [fzlee/alipay#48]
python3对中文的支持比较好，如果无需兼容python2的话，代码会优雅很多，更符合python之禅，所以建议完全迁移到py3

**Comment by fzlee** [comment]
我个人是不介意丢掉Python 2的， 但是到时候只怕会有不少用户过来抱怨。

目前来说， 会继续提供对二者的支持， 原因如下
1. 一些历史的项目，估计想要整体迁移到Python 3 确实不容易。
2. Django 之所以可以不兼容Python 2， 是因为他们有LTS的版本，可以支持Python 2到至少2020年。
3. 现在同时兼容Python 2 和3 对代码的整洁，架构，性能等都没有太大影响。
