### ISSUE TITLE
大神你好，没有考虑过tornado的异步吗

### ISSUE THREAD

**Issue by 2811299** [fzlee/alipay#53]
could support tornado’s asynchronous feature?

**Comment by fzlee** [comment]
我对tornado不太熟悉， 可以详细描述一下你的需求吗？

**Comment by 2811299** [comment]
你在做http请求时候是 同步的， 这样在tornado框架下 使用的话 所有的请求都会被卡住
好像是这样，所以不能直接用request或者urllib请求， 只能用tornado的asynchttprequest方法
所以我没直接用你这个， 而是参考着你的代码写的，改起来的话 其实应该只需要增加对 http请求 另一个种封装就可以了， 如果这样的话tornado也可以用了， 好像是这样我也不太懂。

**Comment by fzlee** [comment]
可以用tornado的`run_in_executor`封装这些请求吗

**Comment by 2811299** [comment]
我用的是tornado的低版本 http请求是由 AsyncHTTPClient 完成的
外面用装饰器@tornado.gen.engine
调用的时候是 yield tornado.gen.Task
我对tornado也不熟， 所以只是单纯的问一下。
