### ISSUE TITLE
生成的sign与网关验签字符串不对应

### ISSUE THREAD

**Issue by zzm88** [fzlee/alipay#54]
这是alipay返回的错误
> 调试错误，请回到请求来源地，重新发起请求。
> 错误代码 invalid-signature 错误原因: 验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：app_id=2018062460380864&amp;biz_content={out_trade_no:20161112,product_code:QUICK_WAP_PAY,total_amount:0.01,subject:subject}&amp;charset=utf-8&amp;method=alipay.trade.wap.pay&amp;notify_url= http://www.getsms.club/&amp;sign_type=RSA2&amp;timestamp=2018-06-26 21:26:52&amp;version=1.0

这是sdk生成的链接
> https://openapi.alipay.com/gateway.do?app_id=2018062460380864&biz_content=%7B%22out_trade_no%22%3A%2220161112%22%2C%22product_code%22%3A%22QUICK_WAP_PAY%22%2C%22total_amount%22%3A0.01%2C%22subject%22%3A%22subject%22%7D&charset=utf-8&method=alipay.trade.wap.pay&notify_url=+http%3A%2F%2Fwww.getsms.club%2F&return_url=&sign_type=RSA2&timestamp=2018-06-26+21%3A26%3A52&version=1.0&sign=略

前者乱入了一些奇怪的amp;

**Comment by zzm88** [comment]
这是我的配置
```
# -*- coding: utf-8 -*-
from alipay import AliPay
from alipay import ISVAlipay
app_private_key_string = open("key/app_private_key.pem").read()
alipay_public_key_string = open("key/alipay_public_key.pem").read()

alipay = AliPay(
    appid="2018062460380864",
    app_notify_url=" http://www.getsms.club/",  # 默认回调url
    app_private_key_string=app_private_key_string,
    alipay_public_key_string=alipay_public_key_string,  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
    sign_type="RSA2", # RSA 或者 RSA2
    debug=False  # 默认False
)


# If you don't know what ISV is, then forget about what I mentioned below
# either app_auth_code or app_auth_token should not be None


# 手机网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
order_string = alipay.api_alipay_trade_wap_pay(
    out_trade_no="20161112",
    total_amount=0.01,
    subject="subject",
    return_url="",
    notify_url="" # 可选, 不填则使用默认notify url
)

url =  'https://openapi.alipay.com/gateway.do?' + order_string
print url
```

**Comment by zzm88** [comment]
搜了下&amp;好像就是&

私钥公钥都是按教程生产的，公钥也放到支付宝后台了，后台上验证私钥公钥是配对的。appid也是对应的。不知道为什么一直说签名错

**Comment by fzlee** [comment]
有两个地方尝试一下， 第一个是url里面的空格，第二个是设置return_url="http:example.com/"， 不要设置为空字符串

**Comment by zzm88** [comment]
```
# -*- coding: utf-8 -*-
from alipay import AliPay
# from alipay import ISVAlipay
app_private_key_string = open("key/app_private_key.pem").read()
alipay_public_key_string = open("key/alipay_public_key.pem").read()


# app_private_key_string = """
#     -----BEGIN RSA PRIVATE KEY-----
#     MIIEpQIBAAKCAQEAwB3pjexgTV1KoQ/e9ycbp5bp8eJ+CEhFBNk0xK4gMi23zDpwkFztVB3Ne9RJAsAYCaD6LIpV7MpEKAHEqvhGlB9h2ONIjX8g6YgvFxSAakLkgmt1aH263vdVnOFYoTVMp/wKDKTMDgur/Z/tYJ/bI/AnIDWn5EZl3DYJKoPU3srSFBywq06vcQfoCpW5ShxUHG3aTFfSf4HG7bLoJ4cTl8nFbbEIdJVvtErstD0QoqwqkHmUHtiEx9iN90k4/Nv10UKUFIdTpTQuNH4Jy5OGymne8esMmIvJKJ02oiSmoVQU7THbKf9tZQPf5wxQp5UAgpcNfW+SxmmSssAzEqNLlQIDAQABAoIBAAvWS/uoos5hfyWpWq2TxUpwK/3xXJ6aBValI3Ey4Vz2ICr/NsxOTXkvVOfaTp1SxKhjOMbhxyWN2OE2Kq32GjMqM9cvOdsuCBMbhvs/EiJ5+KZohJVpmcf/KVE/OTzFkfGPv/bDeKcs5O39mpynfNMcCu0bITsZc1E8KxhpgwYvEZDwhLA24EPoiAmuub9ZjVQvxupWQkNbulM2nla4nWTQwNs4hMMiAtW6TiBj++sfHAH9cys/G2sOko4KN/AsTdYohzfgbTQzdrhWDbxnqKc24iQHl8rNiTO6kZkBb3yyeue2iT9REJMgz+OgZYvMYsH1wNsZuvUygxsBdKY8/8kCgYEA8YgkKszqL3cKM1Ey5sDpkU+GLU4P4iWK8A/igjzCc7i9YRpidsK4rYSR2IAZ1xuSbUdUq+C3ME4Z+9456IJGuaEPBskh+wc4RUbAg34Fe0ET/AQaZNH7cbdqJaoU18HOz/PDia44XHbr1SIOgRTDsnGJeJ/lN8VLg8vH+9hDVfcCgYEAy5//xhuJHQa/Mv+1h3ffKOMmn4u11R1bSAj90bwsdnH+uAMVxA3+XINV7yKiACVnI8sk1W7NWWkCDOyBboEpNGyo4JLN4kb1w+rGZU6bi4tkwywWqGJwIp13Mrk7hXM9RltaOUZgftl3Evu/u8fy/04CXy1B85t2CPkxS6lX19MCgYEAlXdWSlY8pdrYqSEaisnewFmiAu9HzP7GmAB8f3PyMYKlTy3wuOWPO3HKf1vmocMiPhXiQ+rv8iii08aVt1jHQ6BzmBNnv9yb6eL6x2R5J+kB4Pb5DmMTYy/JtD0oYMxCm1WSL+VsY2wETQSiTSb4Y7j3BXqNcpHZRVoaC7OtF8kCgYEAocLObzPqvfthIwOO0zqANrwVL8PORKoYnOY/tUFW1RWEM+yHewNe4WGYf+u0ZIdSI1Y7Qa7PRUstTNUJkZ7b/ACiPB2Dn1Gd5fD5gPtsh/PJrV619TiWOnl7evk59q7wq5bg2wU0nTDm7la+H1Adk4IGUlPiw8LphwFnjuLNnO8CgYEAlhePXPAojfi35ZjzAi6yAp9RhUqB4OSqyVOZFFUA1iOWUUk0dmtv5fVeqxTulG3AY3t1PNaP5rDo6gVKV1SjLYwYNh3Xy2tPEV1gW1SHYpRJ5WTj6Iv/uoBlg9YUkPlXEDNhBoeKUcIzR+6R1fEv4+47nTTdl/IVFsHumyrmz4k=
#     -----END RSA PRIVATE KEY-----
# """

# alipay_public_key_string = """
    # -----BEGIN PUBLIC KEY-----
    # MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwB3pjexgTV1KoQ/e9ycbp5bp8eJ+CEhFBNk0xK4gMi23zDpwkFztVB3Ne9RJAsAYCaD6LIpV7MpEKAHEqvhGlB9h2ONIjX8g6YgvFxSAakLkgmt1aH263vdVnOFYoTVMp/wKDKTMDgur/Z/tYJ/bI/AnIDWn5EZl3DYJKoPU3srSFBywq06vcQfoCpW5ShxUHG3aTFfSf4HG7bLoJ4cTl8nFbbEIdJVvtErstD0QoqwqkHmUHtiEx9iN90k4/Nv10UKUFIdTpTQuNH4Jy5OGymne8esMmIvJKJ02oiSmoVQU7THbKf9tZQPf5wxQp5UAgpcNfW+SxmmSssAzEqNLlQIDAQAB
    # -----END PUBLIC KEY-----
# """

alipay = AliPay(
    appid="2018062460380864",
    app_notify_url="http://www.getsms.club/",  # 默认回调url
    app_private_key_string=app_private_key_string,
    alipay_public_key_string=alipay_public_key_string,  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
    sign_type="RSA2", # RSA 或者 RSA2
    debug=False  # 默认False
)


# If you don't know what ISV is, then forget about what I mentioned below
# either app_auth_code or app_auth_token should not be None

# isv_alipay = ISVAliPay(
#     appid="",
#     app_notify_url=None,  # 默认回调url
#     app_private_key_srting="",
#     alipay_public_key_string="", # alipay public key, do not use your public key!
#     sign_type="RSA", # RSA or RSA2
#     debug=False,  # False by default,
#     app_auth_code=None,
#     app_auth_token=None
# )


# 如果你是Python 2用户（考虑考虑升级到Python 3吧），请确保非ascii的字符串为utf8编码：
subject = u"aaa".encode("utf8")


# 手机网站支付，需要跳转到https://openapi.alipay.com/gateway.do? + order_string
order_string = alipay.api_alipay_trade_wap_pay(
    out_trade_no="20161112",
    total_amount=0.01,
    subject=subject,
    return_url="http://example.com",
    notify_url="" # 可选, 不填则使用默认notify url
)
# url =  'https://openapi.alipaydev.com/gateway.do?' + order_string
url = 'https://openapi.alipay.com/gateway.do?' + order_string
print url
```
输出

> https://openapi.alipay.com/gateway.do?app_id=2018062460380864&biz_content=%7B%22out_trade_no%22%3A%2220161112%22%2C%22product_code%22%3A%22QUICK_WAP_PAY%22%2C%22total_amount%22%3A0.01%2C%22subject%22%3A%22aaa%22%7D&charset=utf-8&method=alipay.trade.wap.pay&notify_url=http%3A%2F%2Fwww.getsms.club%2F&return_url=http%3A%2F%2Fexample.com&sign_type=RSA2&timestamp=2018-06-27+21%3A11%3A44&version=1.0&sign=Iu%2Fq%2BkQwJQ%2BsH%2FtTEXAck54OOSnoF1DsgPELgxRgxa670yORDNIRdastkSmbtyAfZlqd2%2FGyyjyJThJ7WmKqgAooqb%2BHoBSnxCusCf0d1D3nPFf2MCidnacB6ZPTcbBxI7CUzC4PKhvZ15b6svUu7rGzIU8pwPRxffwYPOhC%2F6uTl3PBSWuhjXKLHwj%2BQBaikpMREBg7aRHLjby1mtTbEHVQfp6%2BlIAuz4C4SHg84osein8TDEidiToPaH7F%2F01LZChkYc%2BjO3vo%2B4CZalivpSEfnOpJw3TM0znVL0e6DJhkYHboWPfwqypYeobFbS9MloCmgH9TVvMr9T6%2F3KIheg%3D%3D

支付宝返回的信息
> 调试错误，请回到请求来源地，重新发起请求。
> 错误代码 invalid-signature 错误原因: 验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：app_id=2018062460380864&amp;biz_content={out_trade_no:20161112,product_code:QUICK_WAP_PAY,total_amount:0.01,subject:aaa}&amp;charset=utf-8&amp;method=alipay.trade.wap.pay&amp;notify_url=http://www.getsms.club/&amp;return_url=http://example.com&amp;sign_type=RSA2&amp;timestamp=2018-06-27 21:11:44&amp;version=1.0

query参数

> app_id: 2018062460380864
> biz_content: {out_trade_no:20161112,product_code:QUICK_WAP_PAY,total_amount:0.01,subject:aaa}
> charset: utf-8
> method: alipay.trade.wap.pay
> notify_url: http://www.getsms.club/
> return_url: http://example.com
> sign_type: RSA2
> timestamp: 2018-06-27+21:11:44
> version: 1.0
> sign: Iu/q+kQwJQ+sH/tTEXAck54OOSnoF1DsgPELgxRgxa670yORDNIRdastkSmbtyAfZlqd2/GyyjyJThJ7WmKqgAooqb+HoBSnxCusCf0d1D3nPFf2MCidnacB6ZPTcbBxI7CUzC4PKhvZ15b6svUu7rGzIU8pwPRxffwYPOhC/6uTl3PBSWuhjXKLHwj+QBaikpMREBg7aRHLjby1mtTbEHVQfp6+lIAuz4C4SHg84osein8TDEidiToPaH7F/01LZChkYc+jO3vo+4CZalivpSEfnOpJw3TM0znVL0e6DJhkYHboWPfwqypYeobFbS9MloCmgH9TVvMr9T6/3KIheg==
>

**Comment by zzm88** [comment]
@fzlee 按您说的试改过来了，还是不行～

**Comment by fzlee** [comment]
这个事情有些奇怪，因为我点击你最后一次生成的链接， 直接在电脑浏览器或者手机浏览器里面是可以代开的。

**Comment by zzm88** [comment]
神奇了，我也能打开了T_T

**Comment by zzm88** [comment]
昨晚确实还不行

**Comment by zzm88** [comment]
很奇怪，难道有延迟？因为我改了一些参数又不行了

**Comment by fzlee** [comment]
改了些什么参数？理论上应该是立即生效的
