### ISSUE TITLE
django通知验证一直FALSE

### ISSUE THREAD

**Issue by zzm88** [fzlee/alipay#55]
```
data = urlparse.parse_qs(request.body)   
signature = data.pop('sign')
success = alipay.verify(data, signature)
```

> request.body如下:
> gmt_create=2018-07-10+14%3A50%3A18&charset=utf-8&gmt_payment=2018-07-10+14%3A50%3A30&notify_time=2018-07-10+14%3A50%3A30&subject=%E5%85%85%E5%80%BC1%E5%85%83&sign=NwhSk2DWQRiV25HQXRXzwvcFh0jJy2D3zQBG%2Bp%2BAzVNFx8whfj0Zmm6eFmX19F2HhiDpqOXJ9NY5lUU0KyugsAbEEOYnc%2Fvrx3KeVniSW7G5jExL8n42tvvVqOgRgwsf7eQqiStEkvgOX55olPeX7JaJS0A0dh%2BlgvScSXR3u330x6xu%2BiX0RXzkBm9%2FhuxDufQ5eR3jJNBWl0nC6NBhjHCwcwZDclo0SEfljSW4wUhN%2FEwLEQvcbU2ghwHQUT1awtZtgA2YEHLDt14S2nz4hre3wFr8LP%2F92Kl1fV2At7tbh7Yej5fQppavtm7huMfHbo7PwIfO94YAAb1wz4G1uQ%3D%3D&buyer_id=2088802801047800&invoice_amount=0.01&version=1.0&notify_id=5ca5872707f24d41d27ff65d6afc6f5m6d&fund_bill_list=%5B%7B%22amount%22%3A%220.01%22%2C%22fundChannel%22%3A%22ALIPAYACCOUNT%22%7D%5D&notify_type=trade_status_sync&out_trade_no=2016111118&total_amount=0.01&trade_status=TRADE_SUCCESS&trade_no=2018071021001004800520919284&auth_app_id=2018062460380864&receipt_amount=0.01&point_amount=0.00&app_id=2018062460380864&buyer_pay_amount=0.01&sign_type=RSA2&seller_id=2088102323393514
> 
> 
> 
> urlparse.parse_qs(request.body) :
> {'app_id': ['2018062460380864'], 'auth_app_id': ['2018062460380864'], 'buyer_id': ['2088802801047800'], 'buyer_pay_amount': ['0.01'], 'charset': ['utf-8'], 'fund_bill_list': ['[{"amount":"0.01","...CCOUNT"}]'], 'gmt_create': ['2018-07-10 14:50:18'], 'gmt_payment': ['2018-07-10 14:50:30'], 'invoice_amount': ['0.01'], 'notify_id': ['5ca5872707f24d41d27...afc6f5m6d'], 'notify_time': ['2018-07-10 14:50:30'], 'notify_type': ['trade_status_sync'], 'out_trade_no': ['2016111118'], 'point_amount': ['0.00'], ...}
>

**Comment by fzlee** [comment]
urlparse.parse_qs(request.body)   得到的结果类似
```python
{'app_id': ['2018062460380864']}
```
拿去验证的数据结构应该是
```python
{'app_id': '2018062460380864'}
```

**Comment by fzlee** [comment]
这个签名验证是必须的，不然会有安全问题


你看看验证签名用的公钥，应该是从支付宝后台下载的。我怀疑你把自己的公钥传进去了

**Comment by 265525** [comment]
我和这位兄弟遇到的问题一样唉。。
