### ISSUE TITLE
AttributeError: module 'alipay' has no attribute 'verify'

### ISSUE THREAD

**Issue by HengyueLi** [fzlee/alipay#57]
网页支付。给出的例子运行之后报错如题。钱到是打过去了。请问一下这是什么问题？

**Comment by fzlee** [comment]
verify 是用于验证支付宝的消息通知。可以贴出报错的栈吗？ 暂时没有头绪

**Comment by HengyueLi** [comment]
127.0.0.1 - - [02/Aug/2018 10:17:41] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/PROJECT/aripayExample/main.py", line 36, in hello_world
    success = alipay.verify(data, signature)
AttributeError: module 'alipay' has no attribute 'verify'

**Comment by fzlee** [comment]
在verify前执行两行代码
```python
print(type(alipay))
print(alipay.__dict__)
success = alipay.verify(data, signature)
```
我有点怀疑你用的不是我的库

**Comment by HengyueLi** [comment]
<class 'module'>
{'AliPayValidationError': <class 'alipay.exceptions.AliPayValidationError'>, '__name__': 'alipay', 'AliPayException': <class 'alipay.exceptions.AliPayException'>, 'encodebytes': <function encodebytes at 0x7f08979351e0>, 'datetime': <class 'datetime.datetime'>, 'PKCS1_v1_5': <module 'Cryptodome.Signature.PKCS1_v1_5' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/Cryptodome/Signature/PKCS1_v1_5.py'>, 'decodebytes': <function decodebytes at 0x7f08979352f0>, '__spec__': ModuleSpec(name='alipay', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f0894b9c048>, origin='/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/__init__.py', submodule_search_locations=['/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay']), 'SHA256': <module 'Cryptodome.Hash.SHA256' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/Cryptodome/Hash/SHA256.py'>, 'RSA': <module 'Cryptodome.PublicKey.RSA' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/Cryptodome/PublicKey/RSA.py'>, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f0894b9c048>, 'ISVAliPay': <class 'alipay.ISVAliPay'>, 'b': <function b at 0x7f089207fa60>, '__package__': 'alipay', '__cached__': '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/__pycache__/__init__.cpython-35.pyc', '__path__': ['/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay'], 'exceptions': <module 'alipay.exceptions' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/exceptions.py'>, 'quote_plus': <function quote_plus at 0x7f089a39a620>, '__doc__': '\n    __init__.py\n    ~~~~~~~~~~\n\n', 'BaseAliPay': <class 'alipay.BaseAliPay'>, 'compat': <module 'alipay.compat' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/compat.py'>, '__file__': '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/__init__.py', 'json': <module 'json' from '/usr/lib64/python3.5/json/__init__.py'>, 'AliPay': <class 'alipay.AliPay'>, 'urlopen': <function urlopen at 0x7f08974d7400>, '__builtins__': {'NotImplementedError': <class 'NotImplementedError'>, 'float': <class 'float'>, '__name__': 'builtins', 'ConnectionError': <class 'ConnectionError'>, 'list': <class 'list'>, 'sorted': <built-in function sorted>, 'enumerate': <class 'enumerate'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'True': True, 'EOFError': <class 'EOFError'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 'repr': <built-in function repr>, 'filter': <class 'filter'>, 'super': <class 'super'>, 'OSError': <class 'OSError'>, 'ReferenceError': <class 'ReferenceError'>, 'TabError': <class 'TabError'>, 'AssertionError': <class 'AssertionError'>, 'range': <class 'range'>, 'SystemError': <class 'SystemError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'copyright': Copyright (c) 2001-2017 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'setattr': <built-in function setattr>, 'ArithmeticError': <class 'ArithmeticError'>, 'AttributeError': <class 'AttributeError'>, 'len': <built-in function len>, 'staticmethod': <class 'staticmethod'>, 'bytes': <class 'bytes'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'UnicodeError': <class 'UnicodeError'>, 'issubclass': <built-in function issubclass>, 'KeyError': <class 'KeyError'>, 'NotImplemented': NotImplemented, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'open': <built-in function open>, 'frozenset': <class 'frozenset'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'StopIteration': <class 'StopIteration'>, 'type': <class 'type'>, 'locals': <built-in function locals>, 'OverflowError': <class 'OverflowError'>, 'sum': <built-in function sum>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'ValueError': <class 'ValueError'>, '__debug__': True, 'property': <class 'property'>, 'reversed': <class 'reversed'>, 'UserWarning': <class 'UserWarning'>, 'ord': <built-in function ord>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'RuntimeError': <class 'RuntimeError'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'bytearray': <class 'bytearray'>, 'compile': <built-in function compile>, 'map': <class 'map'>, 'object': <class 'object'>, 'BufferError': <class 'BufferError'>, 'max': <built-in function max>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'classmethod': <class 'classmethod'>, 'TimeoutError': <class 'TimeoutError'>, 'hex': <built-in function hex>, 'IndentationError': <class 'IndentationError'>, 'str': <class 'str'>, 'EnvironmentError': <class 'OSError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'callable': <built-in function callable>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'hasattr': <built-in function hasattr>, 'id': <built-in function id>, 'eval': <built-in function eval>, 'memoryview': <class 'memoryview'>, 'pow': <built-in function pow>, 'iter': <built-in function iter>, 'int': <class 'int'>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'all': <built-in function all>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'ImportWarning': <class 'ImportWarning'>, 'IsADirectoryError': <class 'IsADirectoryError'>, '__import__': <built-in function __import__>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'divmod': <built-in function divmod>, 'dir': <built-in function dir>, 'IOError': <class 'OSError'>, 'Exception': <class 'Exception'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'license': See http://www.python.org/3.5/license.html, 'LookupError': <class 'LookupError'>, 'abs': <built-in function abs>, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 'hash': <built-in function hash>, 'BaseException': <class 'BaseException'>, 'False': False, 'set': <class 'set'>, '__build_class__': <built-in function __build_class__>, 'ChildProcessError': <class 'ChildProcessError'>, '__package__': '', 'NameError': <class 'NameError'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'dict': <class 'dict'>, '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'InterruptedError': <class 'InterruptedError'>, 'SyntaxError': <class 'SyntaxError'>, 'next': <built-in function next>, 'BytesWarning': <class 'BytesWarning'>, 'complex': <class 'complex'>, 'oct': <built-in function oct>, 'FileExistsError': <class 'FileExistsError'>, 'RecursionError': <class 'RecursionError'>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'ImportError': <class 'ImportError'>, 'zip': <class 'zip'>, 'any': <built-in function any>, 'MemoryError': <class 'MemoryError'>, 'IndexError': <class 'IndexError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'FutureWarning': <class 'FutureWarning'>, 'input': <built-in function input>, 'ascii': <built-in function ascii>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'None': None, 'help': Type help() for interactive help, or help(object) for help about object., 'delattr': <built-in function delattr>, 'vars': <built-in function vars>, 'print': <built-in function print>, 'slice': <class 'slice'>, 'FloatingPointError': <class 'FloatingPointError'>, 'tuple': <class 'tuple'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'bin': <built-in function bin>, 'min': <built-in function min>, 'GeneratorExit': <class 'GeneratorExit'>, 'bool': <class 'bool'>, 'PermissionError': <class 'PermissionError'>, 'Ellipsis': Ellipsis, 'TypeError': <class 'TypeError'>, 'SystemExit': <class 'SystemExit'>, 'exec': <built-in function exec>, 'round': <built-in function round>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'format': <built-in function format>, 'chr': <built-in function chr>, 'Warning': <class 'Warning'>, 'isinstance': <built-in function isinstance>}, 'SHA': <module 'Cryptodome.Hash.SHA' from '/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/Cryptodome/Hash/SHA.py'>}

**Comment by fzlee** [comment]
alipay = Alipay(....)
然后alipay.verify()就好了

你应该是import alipay之后直接使用了

**Comment by HengyueLi** [comment]
非常感谢，可以用了。之前是我的理解有误。
