### ISSUE TITLE
请求参数为什么和官方方的SDK不一样？

### ISSUE THREAD

**Issue by HengyueLi** [fzlee/alipay#58]
另外我还有个问题。我注意到官方也出了一个SDK（然而目前并不好用），其中需要输入sub_merchant这个参数（商户ID），为什么你的库里面不需要这个信息呢？           将来会不会出现接口不想容的问题呢？

**Comment by fzlee** [comment]
有具体的sdk，或者文档地址吗？ 我找了一圈， 没有看到

**Comment by HengyueLi** [comment]
https://pypi.org/project/alipay-sdk-python/

**Comment by fzlee** [comment]
![screen shot 2018-08-02 at 10 41 08](https://user-images.githubusercontent.com/1934773/43559432-9b78f3c8-9640-11e8-9900-d4da9fbc8aad.png)

https://docs.open.alipay.com/api_1/alipay.trade.app.pay
这个sub_merchant不是必选的。 对于biz_content，如果你想传入更多的参数， 可以直接放到接口函数里面。具体你可以去看看源代码。


比如api_alipay_trade_app_pay，可以把sub_merchant直接放到函数参数里面去

```python
    def api_alipay_trade_app_pay(
        self, subject, out_trade_no, total_amount, notify_url=None, **kwargs
    ):
        biz_content = {
            "subject": subject,
            "out_trade_no": out_trade_no,
            "total_amount": total_amount,
            "product_code": "QUICK_MSECURITY_PAY"
        }
        biz_content.update(kwargs)
        data = self.build_body("alipay.trade.app.pay", biz_content, notify_url=notify_url)
        return self.sign_data(data)
```
