### ISSUE TITLE
交易查询 error

### ISSUE THREAD

**Issue by HengyueLi** [fzlee/alipay#59]
如例子中那样，alipay = AliPay(appid="", ...)，我直接运行
    result = alipay.api_alipay_trade_query(out_trade_no='....')
    print(result.get("trade_status", ""))

Traceback (most recent call last):
  File "/home/PROJECT/aripayExample/MyAlipayInterface.py", line 111, in <module>
    result = f.AliPayClient.api_alipay_trade_query(out_trade_no='201808020882')
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/__init__.py", line 305, in api_alipay_trade_query
    return self._verify_and_return_sync_response(raw_string, "alipay_trade_query_response")
  File "/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/__init__.py", line 517, in _verify_and_return_sync_response
    sign = response["sign"]
KeyError: 'sign'

**Comment by fzlee** [comment]
直接修改包的源代码， 在/home/PROJECT/code/LibEnv/lib/python3.5/site-packages/alipay/init.py 517 行前print(response) 试试， 看看输出了什么东西

**Comment by HengyueLi** [comment]
{'alipay_trade_query_response': {'sub_code': 'isv.invalid-app-id', 'code': '40002', 'sub_msg': '无效的AppID参数', 'msg': 'Invalid Arguments'}}

感觉AppID应该没问题的样子，因为付款功能可以用。

**Comment by fzlee** [comment]
你是用了ISVAlipay 吗， 看报错说的是isv.invalid-app-id'， 其他的问题我不是很清楚了

**Comment by HengyueLi** [comment]
我并不知道这是什么东西。。。如果我不小心用了什么东西的话  能取消吗？

**Comment by fzlee** [comment]
贴代码上来看一看吧

**Comment by fzlee** [comment]
看看这个吧，确认你有这个接口的权限。
https://openclub.alipay.com/read.php?tid=3147&fid=57

**Comment by fzlee** [comment]
沙箱测试需要 debug=True

H. Li <notifications@github.com> 于2018年8月2日周四 下午6:36写道：

**Comment by HengyueLi** [comment]
原来如此。明白了，谢谢！
