### ISSUE TITLE
cannot import name OSRNG

### ISSUE THREAD

**Issue by pengaman** [fzlee/alipay#6]
上传到服务器之后报错，
Exception Value:
cannot import name OSRNG
Exception Location:
/usr/local/lib/python2.7/dist-packages/alipay/__init__.py in <module>, line 12

**Comment by fzlee** [comment]
这个项目依赖`pycrypto`，初步感觉是这个包没有安装或者安装出错了。
可否给出更加详细的错误日志？
你的软件包是用pip安装的吗，如果可以，可否`pip freeze` 列出安装的全部python依赖。

**Comment by pengaman** [comment]
因为我 pip install pycrypto后没有Cro那个包，不知道是安装版本问题还是我服务器配置问题，我在本地找到了这个包，上传到服务器就没有这个问题了
