### ISSUE TITLE
支付宝回调通知的问题

### ISSUE THREAD

**Issue by lisper-inmove** [fzlee/alipay#66]
`signature = data.pop("sign")
success = alipay.verify(data, signature)
if success and data["trade_status"] in ("TRADE_SUCCESS", "TRADE_FINISHED" ):
    print("trade succeed")
`

这里的alipay是哪来的啊?

我用alipay.AliPay创建出来的对象调用,返回的是fail.

我在回调函数中调用AliPay时用的和之前调用支付宝接口前用的参数是一样的。

**Comment by fzlee** [comment]
alipay就是前面初始化得到的实例。

如果验证失败，请确认传入公钥是从支付宝官网下载，而不是你自己生成的

**Comment by lisper-inmove** [comment]
是从支付宝官风的那个。我这里一共保存了两个key嘛,一个我自己的私钥,一个支付宝的公钥,支付的时候都传了,他调我的notify的那个接口的时候我用的一样的key去初始化这个对象的.就会verify false.不知道是不是哪错了

**Comment by fzlee** [comment]
print(data) 看看，你的data可能不是字典

**Comment by lisper-inmove** [comment]
是字典的，前面处理都没问题，只是返回了false

**Comment by fzlee** [comment]
你的调用方法都没有问题，所以理论上应该返回成功。

建议在源代码里面多print一些信息，来调试代码。

如果你可以贴上验证部分的代码，我也可以帮着看看原因

**Comment by lisper-inmove** [comment]
```
    # data = request.form.to_dict()
    # sign must be poped out
    signature = data.pop("sign")

    alipay = AliPay(
      appid = app.config.get(V.alipay).get(V.app_id),
      app_notify_url="http://47.107.47.171/pay/notifaction",
      app_private_key_path = app.config.get(V.prikey),
      alipay_public_key_path = app.config.get(V.pubkey),  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
      sign_type="RSA2" # RSA 或者 RSA2
    )

    # verify
    # success = alipay.verify(data, signature)
    success = True
    if success and data["trade_status"] in ("TRADE_SUCCESS", "TRADE_FINISHED" ):
        print("trade succeed")
    return RetCode.r(RetCode.SUCCESS, {})

```
生成alipay对象的调用方法倒是一样的，用的两个key也都是一样的.

**Comment by fzlee** [comment]
你用的是flask 吗，就你目前贴上来的所有信息来看，没有任何问题。

**Comment by lisper-inmove** [comment]
是的,flask.两个方法里面初始化不同的AliPay的对象，会有问题吗?

**Comment by lisper-inmove** [comment]
再里面的代码看起来就有点吃力了...

**Comment by lisper-inmove** [comment]
if em1 not in possible_em1:
    raise ValueError("Invalid signature")
pass

进到这个raise了

**Comment by lisper-inmove** [comment]
pkcs8的能用吗?有朋友给我的key他说是什么pkcs8的.

**Comment by fzlee** [comment]
两个不同方法里面，只要初始化参数一样，初始化不同alipay不会有任何影响。

我这边遇到的verify失败一般有这些原因:

1. 传的alipay公钥传错了，或者不小心传了自己的公钥，或者从支付宝官网下载了错误的公钥
2.sign不参与签名检验，却没有从data里面pop出来。(你应该不是这个问题)
3.传入的data不是字典

除此之外没有遇到其他因素导致验证失败的

**Comment by fzlee** [comment]
只要alipay对象能够被构造出来，就不会有问题的。因为初始化的时候就会尝试创建对应的公钥，私钥成员

**Comment by fzlee** [comment]
为啥用支付宝公钥验证签名的问题，涉及到非对称加密的原理。这是为了证明请求确实是由支付宝发起，而不是其他服务器伪造

**Comment by lisper-inmove** [comment]
支付宝有我的公钥,他是不是应该用我的公钥加密?我这边为什么不是用我自己的私钥，而要用支付宝的公钥验签呢?我是这里没明白.

**Comment by fzlee** [comment]
你用自己的私钥签名自己的请求，将请求发送给支付宝，支付宝用你的公钥验证你发过去的请求。
支付宝用自己的私钥签名支付宝自己的请求，你这边收到支付宝请求之后，你用支付宝的公钥验证支付宝的请求。

**Comment by fzlee** [comment]
好奇有找到原因吗

**Comment by cxinde** [comment]
这大哥为啥close了。。。
我也一样问题，验证失败，找不到原因。。。

**Comment by lisper-inmove** [comment]
不记得原因了,放代码的机器被停掉了.
