### ISSUE TITLE
貌似支付宝更新支付接口了，需要签名

### ISSUE THREAD

**Issue by HadXu** [fzlee/alipay#7]
支付宝接口需要 “商户请求参数的签名串，详见签名“

**Comment by fzlee** [comment]
可以给出你调用接口的具体方法吗？我这边目前是好的。

**Comment by HadXu** [comment]
我也不知道哪里有问题，能加qq联系么，调用的是app支付

**Comment by fzlee** [comment]
我不太用QQ老实说，你可以贴上生成order_string的部分代码，我可以帮忙看看

**Comment by HadXu** [comment]
```
alipay = AliPay(appid=Config.ALIPAY_PARTNER_ID, app_private_key_path=Config.ALIPAY_PRIVATE_KEY,
                app_alipay_public_key_path=Config.ALIPAY_PUBLIC_KEY, sign_type='RSA2',
                app_notify_url=Config.ALIPAY_NOTIFY_URL)

order_string = alipay.create_app_trade(out_trade_no="20161112", total_amount="0.01", subject="testing order")
```

**Comment by fzlee** [comment]
你的接口调用方法应该没有问题。你可以帮忙确认以下几件事情吗？
1. 我看见你的appid是ALIPAY_PARTNER_ID。你要确认这个确实是用于app支付的appid。
2. 试试将total_amount变为`0.01`而不是`"0.01"`.
3. 尝试调用这个方法`alipay.create_wap_trade`在浏览器里面尝试支付一笔订单。
4. 给出支付宝报错的完整输出，后台或者浏览器报的错都可以

**Comment by HadXu** [comment]
好 我现在调试

**Comment by HadXu** [comment]
能给一个简便的联系方式么，github上聊天有点怪

**Comment by fzlee** [comment]
fzleee@gmail.com 邮件吧

**Comment by HadXu** [comment]
可以

**Comment by fzlee** [comment]
![image](https://cloud.githubusercontent.com/assets/1934773/23205014/66f43ef2-f923-11e6-9e10-50e232b70844.png)
环境配置问题，和这个库无关

**Comment by HadXu** [comment]
恩恩 调试好了 多谢帮助
