### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by alaikis** [fzlee/alipay#70]
binascii.Error: Incorrect padding

**Comment by alaikis** [comment]
![image](https://user-images.githubusercontent.com/30462479/50851868-fd887700-13b8-11e9-8dad-a6d2a5ff1482.png)

**Comment by fzlee** [comment]
There should be something wrong with the public key, please go and take a look at the cert example [here](https://github.com/fzlee/alipay/tree/master/tests/certs)

**Comment by alaikis** [comment]
but we can make pay but callback

**Comment by fzlee** [comment]
As I have mentioned, there could be something wrong with your alipay public cert. you should double check it and making sure it's adhere to standards,  we have some cert examples located in `certs` folder, you may go and take a look
