### ISSUE TITLE
api异常未能提示

### ISSUE THREAD

**Issue by UbunGit** [fzlee/alipay#71]
v1.9
![image](https://user-images.githubusercontent.com/8732001/50949295-982fa580-14e0-11e9-80c6-0aae2440cf7f.png)
![image](https://user-images.githubusercontent.com/8732001/50949314-a8e01b80-14e0-11e9-8927-8c96b2c33b07.png)

**Comment by fzlee** [comment]
你这边是python 2 吗？可能是因为没有定义__str__导致的。最新的代码已经提交，等待下次发布
