### ISSUE TITLE
python3.7  pip安装报错.

### ISSUE THREAD

**Issue by DaveIW2034** [fzlee/alipay#76]

**Comment by DaveIW2034** [comment]
src/common.h:62:9: error: unknown type name '__int8'; did you mean '__int8_t'?

**Comment by fzlee** [comment]
我这边 MacOS， Python 3.7.1 安装最新版本没有问题。 请提供你的系统环境以及详细的报错内容

**Comment by DaveIW2034** [comment]
python3.7.6 MacOs

**Comment by fzlee** [comment]
详细报错内容有吗

**Comment by DaveIW2034** [comment]
我上边复制粘的的就是, 用pip2 install 解决了, 然后无耻的考到了venv环境中:)

**Comment by fzlee** [comment]
详细的报错指的是报错的调用栈，仅仅提供一个`src/common.h:62:9`会让人摸不着头脑， 不知道究竟哪个地方出了问题。

**Comment by DaveIW2034** [comment]
了解是一个调用栈, 我回家再重新试一下, 把具体的错误粘出来
