### ISSUE TITLE
你的alipay出了问题

### ISSUE THREAD

**Issue by 265525** [fzlee/alipay#79]
在我尝试的时候，我的数据的value出现了列表，我试着修改源代码，但是没有任何效果，希望你能改进一下这个数据处理。

**Comment by fzlee** [comment]
可以给出调用的例子吗

**Comment by 265525** [comment]
https://github.com/fzlee/alipay/issues/55

我用的也是django，但是数据体结构和这个帖子里的一模一样，我尝试着修改源代码让他不报错，但是没有效果。仍然是false

**Comment by 265525** [comment]
公钥与私钥检查过了的，没有错误
        data = dict(request.POST)
        print(data)
        signature = data.pop("sign",None)
        alipay = MyAliPay().pay()
        success = alipay.verify(data, signature)
        if success and data["trade_status"] in ("TRADE_SUCCESS", "TRADE_FINISHED" ):
            print("trade succeed")
            return HttpResponse('支付成功')
        else:
            print('axaxax')
            return HttpResponse('支付失败')

**Comment by 265525** [comment]
数据大概样子:eipt_amount': ['1.00'], 'point_amount': ['0.00'], 'app_id': ['2016100100637059'], 'buyer_pay_amount': ['1.00'], 'sign_type': ['RSA2'], 'seller_id': ['2088102178058233']}>

**Comment by 265525** [comment]
版本django2.13

**Comment by fzlee** [comment]
传入验证的字典需要像这个样子：
```
{
    "eipt_amount": "1.00".
    "app_id": "app_id"
}
```

而不是你提供的例子里面的那样， 值都是列表。Django应该有相关方法转换请求体

**Comment by 265525** [comment]
我知道，但是我不知道如何去传，Python貌似也没有这个方法，单独转的话将会会麻烦。用你官方文档中的url转也是值里面嵌套着列表

**Comment by fzlee** [comment]
Django POST请求拿到的是QueryDict对象，你需要仔细看看[QueryDict](https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.QueryDict)的文档， 用它自带的一方法就可以解决你的问题， 并不需要复杂的代码

**Comment by 265525** [comment]
谢谢！
