### ISSUE TITLE
扫码付接口

### ISSUE THREAD

**Issue by wsqy** [fzlee/alipay#8]
自己实现的扫码付接口   https://github.com/wsqy/ALIPay
其中签名、 验签部分大量使用了你的项目中的代码   请多多批评

**Comment by fzlee** [comment]
哈哈哈，谈不上什么批评。你的代码挺好的。

就是有一段代码比较奇怪，移除这段代码感觉也是可以的？
```
reload(sys)
sys.setdefaultencoding('utf-8')
```
