### ISSUE TITLE
result = alipay.api_alipay_trade_query(out_trade_no="out_trade_no") 有一定的机率会失败

### ISSUE THREAD

**Issue by autodataming** [fzlee/alipay#83]
result = alipay.api_alipay_trade_query(out_trade_no="out_trade_no")
交易预创建，有一定的机率会失败？
result 只有这4个key
dict_keys(['code', 'msg', 'sub_code', 'sub_msg'])

**Comment by fzlee** [comment]
失败报错有吗？顺便提供一下具体的运行环境

**Comment by autodataming** [comment]
不报错，WIN10,Centos,python2.7都试过。应该和你代码没有关系，估计是支付宝后台没有成功响应。

**Comment by fzlee** [comment]
所以具体是哪里失败了？ 可以详细描述一下吗。

支付宝这么大一个平台， 他们出错的机率比较小
