### ISSUE TITLE
希望增加查询商户余额API

### ISSUE THREAD

**Issue by yangyide** [fzlee/alipay#84]
希望实现查询商户余额API alipay.user.account.get ， 现在要定期去登录支付宝的系统，查看余额，比较麻烦。

**Comment by fzlee** [comment]
有对应文档的地址吗， 我在他们文档平台上没有看到

**Comment by yangyide** [comment]
这个上面看到的https://jaq-doc.alibaba.com/docs/api.htm?spm=a313e.7395905.0.0.126f51c3vVu5oC&apiId=11099，  不知道是不是和https://docs.open.alipay.com/api_1用sdk一样。

**Comment by fzlee** [comment]
这是两个不同的系统， 接口不能通用的
