### ISSUE TITLE
签名校验错误

### ISSUE THREAD

**Issue by qunge5211314** [fzlee/alipay#90]
支付宝回调接口使用该sdk时，verify方法总是返回False，支付宝请求参数如下，如需公私钥对请私聊我，QQ：635343793
{'gmt_create': '2019-08-26 16:35:39', 'charset': 'utf-8', 'gmt_payment': '2019-08-26 16:35:45', 'notify_time': '2019-08-26 16:38:18', 'subject': '支付测试', 'sign': 'YON5sCphiiIpkBvbx0pBLgrZs+Ztj3J6mcMVPz8pkTOnt/qKrO6H8n/o/8LvnWSNytGReyl4j+yjuGd2Z/QRMRzjWn3NUEwXA+56lrAC9VecOoGsKi3hEdLMP2HGDB+GH6nKt7zyceIeBpknI+0jfAu0a/lf+4uszPCNbUt/9jCIj7A7Pd3F2DmhcYC9R/Es7QXRBe4HR6zu6HUiHSlqXoPMcN2Lzj+ANBrbLvBfPsqFTw8afepYFW9abcB9DGFKCV4Re2DW051Ru5Y7vRfW8S5a+rHVdHUxy9xU6odrWlxVkm5waW5JiblqipplCqcpPzp3l0fairR6i3i8bXoc0A==', 'buyer_id': '2088902313030625', 'invoice_amount': '0.01', 'version': '1.0', 'notify_id': '2019082600222163545030620533851730', 'fund_bill_list': '[{"amount":"0.01","fundChannel":"ALIPAYACCOUNT"}]', 'notify_type': 'trade_status_sync', 'out_trade_no': 'pay_test11', 'total_amount': '0.01', 'trade_status': 'TRADE_SUCCESS', 'trade_no': '2019082622001430620542154863', 'auth_app_id': '2019011463005038', 'receipt_amount': '0.01', 'point_amount': '0.00', 'buyer_pay_amount': '0.01', 'app_id': '2019011463005038', 'sign_type': 'RSA2', 'seller_id': '2088901259749895'}

**Comment by fzlee** [comment]
verify部分的代码是什么样子的？

**Comment by qunge5211314** [comment]
源代码：
def verify(self, data, signature):
        if "sign_type" in data:
            sign_type = data.pop("sign_type")
            if sign_type != self._sign_type:
                raise AliPayException(None, "Unknown sign type: {}".format(sign_type))
        # 排序后的字符串
        unsigned_items = self._ordered_data(data)
        message = "&".join(u"{}={}".format(k, v) for k, v in unsigned_items)
        return self._verify(message, signature)

    def _verify(self, raw_content, signature):
        # 开始计算签名
        key = self.alipay_public_key
        signer = PKCS1_v1_5.new(key)
        if self._sign_type == "RSA":
            digest = SHA.new()
        else:
            digest = SHA256.new()
        digest.update(raw_content.encode("utf8"))
        if signer.verify(digest, decodebytes(signature.encode("utf8"))):
            return True
        return False

调用代码：
alipay = AliPay(APP_ID, NOTIFY_URL, app_private_key_string=PRIVATE_KEY, alipay_public_key_string=PUBLIC_KEY)
    print(data)
    temp_sign = data.pop("sign")
    check = alipay.verify(data, temp_sign)
    if not check:
        return custom(-1, "签名错误")

**Comment by fzlee** [comment]
用来验证的data的数据结构是什么样子的

**Comment by qunge5211314** [comment]
字典，使用的是flask中的request.form.to_dict()

**Comment by fzlee** [comment]
从你提供的信息来看，都没有什么问题。

如果验证还不通过，那么我猜想你是不是初始化alipay对象的时候，传入的PUBLIC_KEY是你自己的公钥而不是支付宝的

**Comment by qunge5211314** [comment]
公私钥都是本地生成并提交支付宝的，难道说支付宝还有别的公钥生成的地方？

**Comment by fzlee** [comment]
支付宝开放平台后台有下载支付宝自己的公钥的地方，
验证支付宝回调需要使用支付宝的公钥
提交支付宝接口请求需要使用你自己的私钥

**Comment by qunge5211314** [comment]
是我们这边公钥搞错了，谢谢
