### ISSUE TITLE
作为受益者，想贡献代码，但不想维护python2的，是否考虑创建2.0版本，只支持python3.6+

### ISSUE THREAD

**Issue by waketzheng** [fzlee/alipay#91]
鉴于ipython、django、sanic的最新安装包都只支持python3，建议主分支采用python3.6+才编写。。。

**Comment by fzlee** [comment]
用户有自由选择软件库的权利， 但库的作者强制用户选择Python的版本不是太合适。

这个库并不是太复杂，尽管现在主力的Python都是3.6+，用Python 3.2-3.4的时候不会有太多区别。

Python2方面，目前需要兼容的地方主要是unicode的转换，代码在compat.py 里面。在新功能添加之后，可以tests里面的代码对项目进行测试,不出错一般就不存在兼容性问题。

**Comment by waketzheng** [comment]
考虑一下吧，没有强制这种说法。就像最新版的Django2.0只支持python3， 但是python2的用户依然可以安装Django1.11的。ipython也一样，最新版是7.8，但是Python2的话，pip install ipython得到的是5.8版的。
