### ISSUE TITLE
请问有支付宝二维码扫码登录的示例计划么？

### ISSUE THREAD

**Issue by sanren99999** [fzlee/alipay#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fzlee** [comment]
这个库仅仅用于支付宝支付， 应该不支持扫码登录

**Comment by sanren99999** [comment]
跪求大佬们支持支付宝扫码登录功能，实现全流程

**Comment by fzlee** [comment]
如果你说的是支付宝oauth登录， 可以参看下面的文档。
https://docs.open.alipay.com/263/105809/

我们这个库最底层提供了最底层的签名操作。

除此之外， 你需要自己实现两个方法 `alipay.system.oauth.token` 和 `alipay.user.info.share`
