### ISSUE TITLE
通知验证似乎失效了

### ISSUE THREAD

**Issue by beebon** [fzlee/alipay#98]
**Describe the bug**
签名本身是验证通过的，但没有返回订单状态，即调用回调地址时并没有传入trade_status参数，导致也不清楚支付状态是如何的（实际在支付交互过程中，已经完成了支付操作然后才自动跳转到回调地址），是不是alipay本身做了什么修改导致不会再继续传入trade_status这个参数了

**Environment**
OS version: Windows 10
Python version:3.7

**To reproduce**
Code snippets:
```python
    # 验证签名是否有效及交易是否成功
    signValid = alipay.verify(param, signature)
    TRADE_SUCCESS = signValid and param["trade_status"] in ("TRADE_SUCCESS", "TRADE_FINISHED" )   
```

**Expected behavior **
验签通过且返回订单状态

**Comment by fzlee** [comment]
请问你是调用是哪个接口创建支付请求， 然后回调给你的参数里面有哪些字段？

**Comment by fzlee** [comment]
长时间没有收到回复， 关闭这个issue
